### ISSUE TITLE
Module 3 exercises [Francisca Ameley Armah-CERSGIS]

### ISSUE THREAD

**Issue by ameley1** [SERVIR-WA/GALUP#104]
1. Please "drag & drop" exercise 1 pdf file below.
[Land Condition Map.pdf](https://github.com/SERVIR-WA/GALUP/files/6816108/Land.Condition.Map.pdf)

2. Please "drag & drop" exercise 2 pdf file below.

[The Market Suitabillity Map of THLD (by IDU).pdf](https://github.com/SERVIR-WA/GALUP/files/6816122/The.Market.Suitabillity.Map.of.THLD.by.IDU.pdf)

3. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.

4. If you haven't done so, please go back to Module 3 and make sure to take
   the post-training survey. Participating in surveys is required for receiving
   the "GALUP Certificate" by the University of Florida.

**Comment by muribasterra** [comment]
Well done, Francisca. Your maps look great, and it is clear that you understand the material in Module 3 and can successfully apply it using the graphical modeler. Thanks for your participation!
