### ISSUE TITLE
Module 1 exercises [SILAS ACHIDAGO]

### ISSUE THREAD

**Issue by Silach57** [SERVIR-WA/GALUP#11]
1. Please drag & drop exercise 1 pdf file below.
[Ghana_Population_2018.pdf](https://github.com/SERVIR-WA/GALUP/files/6591609/Ghana_Population_2018.pdf)

2. Please drag & drop exercise 2 pdf file below.
[Population_Density_2018.pdf](https://github.com/SERVIR-WA/GALUP/files/6608971/Population_Density_2018.pdf)

3. Make sure to update the title with your name.

4. Post-training Survey (required)

   (1) Time needed to complete:
     (1.1) How long did you need to go through module 1?
ANS: Two (2) days
     (1.2) How long did it take you to go through exercise 1?
ANS: One (1) day
     (1.3) How long did it take you to go through exercise 2?
ANS: One (1) day

   (2) Content of the course:
     (2.1) Did you experience any difficulties with the instructions?
ANS: No difficulty experienced
     (2.2) Could you list any portions that were more difficult for you to complete?
ANS: N/A
   (3) Did you learn anything new?
ANS: I learnt a few more functions in the Field Calculator video
     (3.1) If yes, please provide details:
ANS: "Concat", "$length" and other functions in a link attached
   (4) Do you have any suggestion on how we could improve future training sessions?
ANS: The initial part is fine. It will be great to have video tutorials when we get to more complicated areas. This will serve as a good reference material anytime participants need to recall some processes.

**Comment by JuliePeeling** [comment]
Well done, Silas. You clearly grasped the material outlined in Module 1 and successfully applied it to these exercises. Thank you for your participation! Please be sure to fill out the post-Module survey before you begin the next Module.
