### ISSUE TITLE
Module 3 exercises [Sheila Humphrey]

### ISSUE THREAD

**Issue by Sheila6868** [SERVIR-WA/GALUP#110]
1. Please "drag & drop" exercise 1 pdf file below.
[BufferClip_Model.zip](https://github.com/SERVIR-WA/GALUP/files/6843966/BufferClip_Model.zip)

[Mod3Exe1_Sheila.pdf](https://github.com/SERVIR-WA/GALUP/files/6843964/Mod3Exe1_Sheila.pdf)

2. Please "drag & drop" exercise 2 pdf file below.
[Mod3Exe2_Sheila.pdf](https://github.com/SERVIR-WA/GALUP/files/6843969/Mod3Exe2_Sheila.pdf)

3. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.

4. If you haven't done so, please go back to Module 3 and make sure to take
   the post-training survey. Participating in surveys is required for receiving
   the "GALUP Certificate" by the University of Florida.

**Comment by muribasterra** [comment]
Well done, Sheila. Your maps look great, and it is clear that you understand the material in Module 3 and can successfully apply it using the graphical modeler. Thanks for your participation
