### ISSUE TITLE
Module 3 exercises [Ama Boadu]

### ISSUE THREAD

**Issue by Amaluspa** [SERVIR-WA/GALUP#112]
1. Please "drag & drop" exercise 1 pdf file below.
[BufferClip_Ama.zip](https://github.com/SERVIR-WA/GALUP/files/6856603/BufferClip_Ama.zip)

[Mod3Ex1_Ama.pdf](https://github.com/SERVIR-WA/GALUP/files/6856599/Mod3Ex1_Ama.pdf)

2. Please "drag & drop" exercise 2 pdf file below.

[Mod3Ex2_Ama.pdf](https://github.com/SERVIR-WA/GALUP/files/6856604/Mod3Ex2_Ama.pdf)

3. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.

4. If you haven't done so, please go back to Module 3 and make sure to take
   the post-training survey. Participating in surveys is required for receiving
   the "GALUP Certificate" by the University of Florida.

**Comment by muribasterra** [comment]
Well done, Ama. Your maps look great, and it is clear that you understand the material in Module 3 and can successfully apply it using the graphical modeler. Thanks for your participation
