### ISSUE TITLE
Module 3 exercises [Amanda Selasie Abla Doagbodzie]

### ISSUE THREAD

**Issue by Selasie89** [SERVIR-WA/GALUP#127]
1. Please "drag & drop" exercise 1 pdf file below.
[LandCondition Index.pdf](https://github.com/SERVIR-WA/GALUP/files/6894294/LandCondition.Index.pdf)
2. Please "drag & drop" exercise 2 pdf file below.
[rcrp_market.pdf](https://github.com/SERVIR-WA/GALUP/files/6894298/rcrp_market.pdf)
[BufferClip.zip](https://github.com/SERVIR-WA/GALUP/files/6894431/BufferClip.zip)
3. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.

4. If you haven't done so, please go back to Module 3 and make sure to take
   the post-training survey. Participating in surveys is required for receiving
   the "GALUP Certificate" by the University of Florida.

**Comment by JuliePeeling** [comment]
Well done, Amanda. You clearly grasped the material outlined in Module 3 and successfully applied it to these exercises. Thank you for your participation! Please be sure to fill out the post-Module survey before you begin the next Module.
