### ISSUE TITLE
Module 1 Test Drive Exercise [Chapman Owusu-Sekyere]

### ISSUE THREAD

**Issue by cosekyere** [SERVIR-WA/GALUP#141]
1. Please "drag & drop" exercise 1 pdf file below.
[Buffer_Clip.zip](https://github.com/SERVIR-WA/GALUP/files/6940266/Buffer_Clip.zip)

2. Please "drag & drop" exercise 2 pdf file below.

3. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.

4. If you haven't done so, please go back to Module 1 and make sure to take
   the post-training survey. Participating in surveys is required for receiving
   the "GALUP Certificate" by the University of Florida.

**Comment by chjch** [comment]
Thank you Mr. Chapman for submitting this exercise. It looks good.
