### ISSUE TITLE
Module 1 exercises [Sheila A. N. Humphrey- Ackumey ]

### ISSUE THREAD

**Issue by Sheila6868** [SERVIR-WA/GALUP#15]
1. Please "drag & drop" exercise 1 pdf file below.
[Sheila- First Assignment.pdf](https://github.com/SERVIR-WA/GALUP/files/6613723/Sheila-.First.Assignment.pdf)

2. Please "drag & drop" exercise 2 pdf file below.
[Sheila- Second Assignment.pdf](https://github.com/SERVIR-WA/GALUP/files/6613725/Sheila-.Second.Assignment.pdf)

3. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.

4. If you haven't done so, please go back to Module 1 and make sure to take
   the post-training survey. Participating in surveys is required for receiving
   the "GALUP Certificate" by the University of Florida.

**Comment by chjch** [comment]
Sheila, both of the two pdf files you turned in above are not accessible. Can you please edit the original issue and redo the "drag & drop"?

**Comment by chjch** [comment]
P.S. You can test whether you successfully uploaded the file by clicking on it (after submission) and see if you can download the pdf file.

**Comment by JuliePeeling** [comment]
Well done, Sheila. You clearly grasped the material outlined in Module 1 and successfully applied it to these exercises. Thank you for your participation! Please be sure to fill out the post-Module survey before you begin the next Module.
