### ISSUE TITLE
Module 4 exercises [Sheila A. N. Humphrey- Ackumey]

### ISSUE THREAD

**Issue by Sheila6868** [SERVIR-WA/GALUP#150]
1. Please "drag & drop" exercise 1 excel file below.
[Sheila- Mod4Exe1_.xlsx](https://github.com/SERVIR-WA/GALUP/files/6951291/Sheila-.Mod4Exe1_.xlsx)

2. Please "drag & drop" exercise 2 excel file below.

[Sheila- Mod4Exe2_xlsx.xlsx](https://github.com/SERVIR-WA/GALUP/files/6951285/Sheila-.Mod4Exe2_xlsx.xlsx) 

3. Please "drag & drop" exercise 3 pdf file below.
[Sheila- Rank Reci Map_..pdf](https://github.com/SERVIR-WA/GALUP/files/6951288/Sheila-.Rank.Reci.Map_.pdf)

[Sheila- Rank Sum Map_..pdf](https://github.com/SERVIR-WA/GALUP/files/6951290/Sheila-.Rank.Sum.Map_.pdf)

4. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.

5. If you haven't done so, please go back to Module 4 and make sure to take
   the post-training survey. Participating in surveys is required for receiving
   the "GALUP Certificate" by the University of Florida.

**Comment by JuliePeeling** [comment]
Well done, Sheila. You clearly grasped the material outlined in Module 4 and successfully applied it to these exercises. Thank you for your participation! Please be sure to fill out the post-Module survey before you begin the next Module.
