### ISSUE TITLE
Module 4 exercises [Ama Boadu]

### ISSUE THREAD

**Issue by Amaluspa** [SERVIR-WA/GALUP#151]
1. Please "drag & drop" exercise 1 excel file below.
[Module4Exercise1..xlsx.xlsx](https://github.com/SERVIR-WA/GALUP/files/6954300/Module4Exercise1.xlsx.xlsx)

2. Please "drag & drop" exercise 2 excel file below.
[Module4Exercise2..xlsx.xlsx](https://github.com/SERVIR-WA/GALUP/files/6954303/Module4Exercise2.xlsx.xlsx)

3. Please "drag & drop" exercise 3 pdf file below.
[Rank Sum Map..pdf](https://github.com/SERVIR-WA/GALUP/files/6954306/Rank.Sum.Map.pdf)
[Rank Reci Map. .pdf](https://github.com/SERVIR-WA/GALUP/files/6954308/Rank.Reci.Map.pdf)

4. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.

5. If you haven't done so, please go back to Module 4 and make sure to take
   the post-training survey. Participating in surveys is required for receiving
   the "GALUP Certificate" by the University of Florida.

**Comment by JuliePeeling** [comment]
Well done, Ama. You clearly grasped the material outlined in Module 4 and successfully applied it to these exercises. Thank you for your participation! Please be sure to fill out the post-Module survey before you begin the next Module.
