### ISSUE TITLE
Module 4 exercises_Stephen Nana Essuman

### ISSUE THREAD

**Issue by StephenNanaEssuman** [SERVIR-WA/GALUP#158]
1. Please "drag & drop" exercise 1 excel file below.
[Module 3_Ex 1.xlsx](https://github.com/SERVIR-WA/GALUP/files/6955368/Module.3_Ex.1.xlsx)

2. Please "drag & drop" exercise 2 excel file below.
[Module 3_Ex 2.xlsx](https://github.com/SERVIR-WA/GALUP/files/6955377/Module.3_Ex.2.xlsx)

3. Please "drag & drop" exercise 3 pdf file below.
[Module 4_Rank_Sum.pdf](https://github.com/SERVIR-WA/GALUP/files/6955383/Module.4_Rank_Sum.pdf)
[Module 4_Rank_Reciprocal.pdf](https://github.com/SERVIR-WA/GALUP/files/6955384/Module.4_Rank_Reciprocal.pdf)

4. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.

5. If you haven't done so, please go back to Module 4 and make sure to take
   the post-training survey. Participating in surveys is required for receiving
   the "GALUP Certificate" by the University of Florida.

**Comment by JuliePeeling** [comment]
Well done, Stephen. You clearly grasped the material outlined in Module 4 and successfully applied it to these exercises. Thank you for your participation! Please be sure to fill out the post-Module survey before you begin the next Module.
