### ISSUE TITLE
Module 4 exercises [Francisca Ameley Armah-CERSGIS]

### ISSUE THREAD

**Issue by ameley1** [SERVIR-WA/GALUP#166]
1. Please "drag & drop" exercise 1 excel file below.
[Module.4.Exercise.1.xlsx](https://github.com/SERVIR-WA/GALUP/files/6956175/Module.4.Exercise.1.xlsx)

2. Please "drag & drop" exercise 2 excel file below.
[Module.4.Exercise.2.xlsx](https://github.com/SERVIR-WA/GALUP/files/6956180/Module.4.Exercise.2.xlsx)

3. Please "drag & drop" exercise 3 pdf file below.
[rank reciprocal.pdf](https://github.com/SERVIR-WA/GALUP/files/6956183/rank.reciprocal.pdf)
[rank sum.pdf](https://github.com/SERVIR-WA/GALUP/files/6956184/rank.sum.pdf)

4. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.

5. If you haven't done so, please go back to Module 4 and make sure to take
   the post-training survey. Participating in surveys is required for receiving
   the "GALUP Certificate" by the University of Florida.

**Comment by JuliePeeling** [comment]
Well done, Francisca. You clearly grasped the material outlined in Module 4 and successfully applied it to these exercises. Thank you for your participation! Please be sure to fill out the post-Module survey before you begin the next Module.
