### ISSUE TITLE
Edwina Asiedu Anderson

### ISSUE THREAD

**Issue by Edwina-Anderson** [SERVIR-WA/GALUP#195]
1. Please "drag & drop" exercise 1 file below.

2. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.

3. If
[Practice One-WS2_M1E1_Submission.docx](https://github.com/SERVIR-WA/GALUP/files/7498804/Practice.One-WS2_M1E1_Submission.docx)
 you haven't done so, please go back to Module 1 and make sure to take
   the post-training survey.

**Comment by JuliePeeling** [comment]
Thank you for your successful submission to the practice exercise! Please be sure to fill out the post-Module survey.
