### ISSUE TITLE
Module 1 exercises [Nathaniel Mensah]

### ISSUE THREAD

**Issue by NathanielMwnsah** [SERVIR-WA/GALUP#208]
1. Please "drag & drop" exercise 1 file below.

2. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.

3. If you haven't done so, please go back to Module 1 and make sure to take
   the post-training survey. 
[WS2_M1E1_Submission.docx](https://github.com/SERVIR-WA/GALUP/files/7505637/WS2_M1E1_Submission.docx)

**Comment by JuliePeeling** [comment]
Thank you for your successful submission to the practice exercise! Please be sure to fill out the post-Module survey.

**Comment by JuliePeeling** [comment]
Hi Nathaniel,
Unfortunately, we do not have you registered in our training program. Could you please provide us with your institution and email? Thank you.
