### ISSUE TITLE
Module 1 exercises [MADJANOR JEDIDIAH]

### ISSUE THREAD

**Issue by madjanorjedidiah** [SERVIR-WA/GALUP#230]
1. Please "drag & drop" exercise 1 file below.

2. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.

3. If you haven't done so, please go back to Module 1 and make sure to take
   the post-training surv
[MODULE1_PracticeTest_Submission.docx](https://github.com/SERVIR-WA/GALUP/files/7511587/MODULE1_PracticeTest_Submission.docx)
ey.

**Comment by luc-oli** [comment]
Thank you for your successful submission to the practice exercise! Please be sure to fill out the post-Module survey.
