### ISSUE TITLE
Prosper Kwame Detornu

### ISSUE THREAD

**Issue by Prosper-Detornu** [SERVIR-WA/GALUP#232]
1. Please "drag & drop" exercise 1 file below.

2. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.

[WS2_M1E1_Prosper Kwame Detornu.docx](https://github.com/SERVIR-WA/GALUP/files/7512409/WS2_M1E1_Prosper.Kwame.Detornu.docx)
3. If you haven't done so, please go back to Module 1 and make sure to take
   the post-training survey.

**Comment by luc-oli** [comment]
Thank you for your successful submission to the practice exercise! Please be sure to fill out the post-Module survey.
