### ISSUE TITLE
 Module 1 exercises [CHAPMAN OWUSU-SEKYERE]

### ISSUE THREAD

**Issue by cosekyere** [SERVIR-WA/GALUP#237]
1. Please "drag & drop" exercise 1 file below.

[WS2_M1E1_Submission.docx](https://github.com/SERVIR-WA/GALUP/files/7513657/WS2_M1E1_Submission.docx)

2. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.

[WS2_M1E1_Submission.docx](https://github.com/SERVIR-WA/GALUP/files/7513656/WS2_M1E1_Submission.docx)

**Comment by luc-oli** [comment]
Thank you for your successful submission to the practice exercise! Please be sure to fill out the post-Module survey.
