### ISSUE TITLE
BOTCHIE_SEYRAM_KWAME

### ISSUE THREAD

**Issue by GitMalachi** [SERVIR-WA/GALUP#240]
[WS2_M2E2_Submission_BOTCHIE_SEYRAM_KWAME.docx](https://github.com/SERVIR-WA/GALUP/files/7529439/WS2_M2E2_Submission_BOTCHIE_SEYRAM_KWAME.docx)

**Comment by JuliePeeling** [comment]
Well done, Botchie. You clearly grasped the material outlined in Module 2 and successfully applied it to these exercises. Thank you for your participation! Please be sure to fill out the post-Module survey before you begin the next Module.
