### ISSUE TITLE
Mananu Salam

### ISSUE THREAD

**Issue by Manansalam** [SERVIR-WA/GALUP#243]
[module 2 assignment.docx](https://github.com/SERVIR-WA/GALUP/files/7532205/module.2.assignment.docx)

**Comment by JuliePeeling** [comment]
Well done, Mananu. You clearly grasped the material outlined in Module 2 and successfully applied it to these exercises. Thank you for your participation! Please be sure to fill out the post-Module survey before you begin the next Module.
