### ISSUE TITLE
Zuta Daniel Narh Module 2

### ISSUE THREAD

**Issue by Daniel-Zuta** [SERVIR-WA/GALUP#245]
[WS2_M2E2_Submission.docx](https://github.com/SERVIR-WA/GALUP/files/7533632/WS2_M2E2_Submission.docx)

**Comment by JuliePeeling** [comment]
Well done, Zuta. You clearly grasped the material outlined in Module 2 and successfully applied it to these exercises. Thank you for your participation! Please be sure to fill out the post-Module survey before you begin the next Module.
