### ISSUE TITLE
Ampadu Boateng Daniel Module 2 exercises 

### ISSUE THREAD

**Issue by DanielBoateng** [SERVIR-WA/GALUP#250]
[WS2_M2E2_Submission.docx](https://github.com/SERVIR-WA/GALUP/files/7534932/WS2_M2E2_Submission.docx)

**Comment by JuliePeeling** [comment]
Well done, Daniel. You clearly grasped the material outlined in Module 2 and successfully applied it to these exercises. Thank you for your participation! Please be sure to fill out the post-Module survey before you begin the next Module.
