### ISSUE TITLE
Module 2 Exercise Madjanor Jedidiah

### ISSUE THREAD

**Issue by madjanorjedidiah** [SERVIR-WA/GALUP#259]
[Uploading WS2_M2E2_Submission_TENNESSEE.docx…]()

**Comment by JuliePeeling** [comment]
Hi Jedidiah, could you reupload your submission? The document did not properly load into Github. Thank you!

**Comment by madjanorjedidiah** [comment]
[WS2_M2E2_Submission_TENNESSEE.docx](https://github.com/SERVIR-WA/GALUP/files/7539811/WS2_M2E2_Submission_TENNESSEE.docx)

**Comment by JuliePeeling** [comment]
Well done, Jedidiah. You clearly grasped the material outlined in Module 2 and successfully applied it to these exercises. Thank you for your participation! Please be sure to fill out the post-Module survey before you begin the next Module.
