### ISSUE TITLE
Module 2 exercises [Richmond Mensah]

### ISSUE THREAD

**Issue by EnochAnchebah** [SERVIR-WA/GALUP#264]
1. Please "drag & drop" exercise 1 file below.

[WS2_M2E2_Submission - Richmond Mensah..docx](https://github.com/SERVIR-WA/GALUP/files/7547110/WS2_M2E2_Submission.-.Richmond.Mensah.docx)

2. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.

3. If you haven't done so, please go back to Module 2 and make sure to take
   the post-training survey. 

Hi, Mr. Richmond Mensah has a problem accessing his github account so he submitted his assignment through my account. Please can this problem be solved? thank you.

**Comment by JuliePeeling** [comment]
Well done, Richmond. You clearly grasped the material outlined in Module 2 and successfully applied it to these exercises. Thank you for your participation! Please be sure to fill out the post-Module survey before you begin the next Module.
