### ISSUE TITLE
Module 2 exercises [replace with your name]

### ISSUE THREAD

**Issue by AfenyaDavidKweku** [SERVIR-WA/GALUP#269]
[WS2_M2E1 Afenya David Kweku.docx](https://github.com/SERVIR-WA/GALUP/files/7548245/WS2_M2E1.Afenya.David.Kweku.docx)

**Comment by JuliePeeling** [comment]
Well done, Afenya. You clearly grasped the material outlined in Module 2 and successfully applied it to these exercises. Thank you for your participation! Please be sure to fill out the post-Module survey before you begin the next Module.
