### ISSUE TITLE
Module 1 exercises [Amanda Sealasie Doagbodzie]

### ISSUE THREAD

**Issue by Selasie89** [SERVIR-WA/GALUP#27]
1. Please "drag & drop" exercise 1 pdf file below.
[Ghana Population Ex 1.pdf](https://github.com/SERVIR-WA/GALUP/files/6610775/Ghana.Population.Ex.1.pdf)
2. Please "drag & drop" exercise 2 pdf file below.
[Population Density EX 2.pdf](https://github.com/SERVIR-WA/GALUP/files/6610769/Population.Density.EX.2.pdf)
3. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.

4. If you haven't done so, please go back to Module 1 and make sure to take
   the post-training survey. Participating in surveys is required for receiving
   the "GALUP Certificate" by the University of Florida.

**Comment by JuliePeeling** [comment]
Well done, Amanda. You clearly grasped the material outlined in Module 1 and successfully applied it to these exercises. Thank you for your participation! Please be sure to fill out the post-Module survey before you begin the next Module.
