### ISSUE TITLE
THEOPHILUS ANUM ADJEI

### ISSUE THREAD

**Issue by Philanu** [SERVIR-WA/GALUP#271]
1. Please "drag & drop" exercise 1 file below.

2. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.

3. If you haven't done so, please g
[WS2_M1E1_Submission_Theophilus Anum  Adjei.docx](https://github.com/SERVIR-WA/GALUP/files/7548455/WS2_M1E1_Submission_Theophilus.Anum.Adjei.docx)
o back to Module 1 and make sure to take
   the post-training survey.

**Comment by JuliePeeling** [comment]
Thank you for your successful submission to the practice exercise! Please be sure to fill out the post-Module survey.
