### ISSUE TITLE
THEOPHILUS ANUM ADJEI

### ISSUE THREAD

**Issue by Philanu** [SERVIR-WA/GALUP#273]
[WS2_M2E2_Submission_Theophilus Anum Adjei.docx](https://github.com/SERVIR-WA/GALUP/files/7554177/WS2_M2E2_Submission_Theophilus.Anum.Adjei.docx)

**Comment by JuliePeeling** [comment]
Well done, Theophilus. You clearly grasped the material outlined in Module 2 and successfully applied it to these exercises. Thank you for your participation! Please be sure to fill out the post-Module survey before you begin the next Module.
