### ISSUE TITLE
Module 1 exercises [Ernest Opoku Kwarteng]

### ISSUE THREAD

**Issue by ernest19** [SERVIR-WA/GALUP#284]
1. Please "drag & drop" exercise 1 file below.

2. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.

3. If you haven't done so, please go back to Module 1 and make sure to take
   the post-training survey. 
[WS2_M1E1_Submission (2).docx](https://github.com/SERVIR-WA/GALUP/files/7575163/WS2_M1E1_Submission.2.docx)

**Comment by JuliePeeling** [comment]
Well done, Ernest. You clearly grasped the material outlined in Module 1 and successfully applied it to these exercises. Thank you for your participation! Please be sure to fill out the post-Module survey before you begin the next Module.
