### ISSUE TITLE
Module 3 exercises [MARVIN AYEH]

### ISSUE THREAD

**Issue by Marvesc** [SERVIR-WA/GALUP#287]
[WS2_M3E1_Template.docx](https://github.com/SERVIR-WA/GALUP/files/7576450/WS2_M3E1_Template.docx)

**Comment by JuliePeeling** [comment]
Well done, Marvin. You clearly grasped the material outlined in Module 3 and successfully applied it to these exercises. Thank you for your participation! Please be sure to fill out the post-Module survey before you begin the next Module.
