### ISSUE TITLE
 Ampadu Boateng Daniel [Module 3 exercises]

### ISSUE THREAD

**Issue by DanielBoateng** [SERVIR-WA/GALUP#307]
[WS2_M3E1_Template.docx](https://github.com/SERVIR-WA/GALUP/files/7595212/WS2_M3E1_Template.docx)

**Comment by JuliePeeling** [comment]
Well done, Daniel. You clearly grasped the material outlined in Module 3 and successfully applied it to these exercises. Thank you for your participation! Please be sure to fill out the post-Module survey before you begin the next Module.
