### ISSUE TITLE
AFENYA DAVID KWEKU M3E1

### ISSUE THREAD

**Issue by AfenyaDavidKweku** [SERVIR-WA/GALUP#308]
[WS2_M3E1.docx](https://github.com/SERVIR-WA/GALUP/files/7595320/WS2_M3E1.docx)

**Comment by JuliePeeling** [comment]
Well done, Afenya. You clearly grasped the material outlined in Module 3 and successfully applied it to these exercises. Thank you for your participation! Please be sure to fill out the post-Module survey before you begin the next Module.
