### ISSUE TITLE
Module 3 exercises [Gideon Anim Kofi Bempong]

### ISSUE THREAD

**Issue by Gideon-Bempong** [SERVIR-WA/GALUP#309]
[WS2_M3E1_Template.docx](https://github.com/SERVIR-WA/GALUP/files/7595380/WS2_M3E1_Template.docx)

**Comment by JuliePeeling** [comment]
Well done, Gideon. You clearly grasped the material outlined in Module 3 and successfully applied it to these exercises. Thank you for your participation! Please be sure to fill out the post-Module survey before you begin the next Module.
