### ISSUE TITLE
Seyram Kwame Botchie

### ISSUE THREAD

**Issue by GitMalachi** [SERVIR-WA/GALUP#313]
[WS2_M3E1_Seyram.docx](https://github.com/SERVIR-WA/GALUP/files/7596162/WS2_M3E1_Seyram.docx)

**Comment by JuliePeeling** [comment]
Well done, Botchie. You clearly grasped the material outlined in Module 3 and successfully applied it to these exercises. Thank you for your participation! Please be sure to fill out the post-Module survey before you begin the next Module.
