### ISSUE TITLE
Zuta Daniel Narh_M3E1

### ISSUE THREAD

**Issue by Daniel-Zuta** [SERVIR-WA/GALUP#317]
[WS2_M3E1.docx](https://github.com/SERVIR-WA/GALUP/files/7598484/WS2_M3E1.docx)

**Comment by luc-oli** [comment]
Well done, Daniel. You clearly grasped the material outlined in Module 3 and successfully applied it to these exercises. Thank you for your participation! Please be sure to fill out the post-Module survey before you begin the next Module.
