### ISSUE TITLE
Edwina Asiedu Anderson

### ISSUE THREAD

**Issue by Edwina-Anderson** [SERVIR-WA/GALUP#320]
1. Please "drag & drop" exercise 3 file below.

2. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.

3. If you haven't done so, please go back t
[Module 3- Edwina..docx](https://github.com/SERVIR-WA/GALUP/files/7609637/Module.3-.Edwina.docx)
o Module 3 and make sure to take
   the post-training survey.

**Comment by JuliePeeling** [comment]
Well done, Edwina. You clearly grasped the material outlined in Module 3 and successfully applied it to these exercises. Thank you for your participation! Please be sure to fill out the post-Module survey before you begin the next Module.
