### ISSUE TITLE
Module 4 exercises [Ernest Opoku-Kwarteng]

### ISSUE THREAD

**Issue by ernest19** [SERVIR-WA/GALUP#332]
[WS2_M4E1_Template.docx](https://github.com/SERVIR-WA/GALUP/files/7632924/WS2_M4E1_Template.docx)

**Comment by JuliePeeling** [comment]
Well done, Ernest. You clearly grasped the material outlined in Module 4 and successfully applied it to these exercises. Thank you for your participation! Please be sure to fill out the post-Module survey before you begin the next Module.
