### ISSUE TITLE
Module 4 exercises [EnochAnchebah]

### ISSUE THREAD

**Issue by EnochAnchebah** [SERVIR-WA/GALUP#343]
[WS2_M4E1_Enoch Anchebah.docx](https://github.com/SERVIR-WA/GALUP/files/7634529/WS2_M4E1_Enoch.Anchebah.docx)

**Comment by JuliePeeling** [comment]
Well done, Enoch. You clearly grasped the material outlined in Module 4 and successfully applied it to these exercises. Thank you for your participation! Please be sure to fill out the post-Module survey before you begin the next Module.
