### ISSUE TITLE
Module 4 exercises [Sheila Abla Nyanyonu Humphrey- Ackumey ]

### ISSUE THREAD

**Issue by Sheila6868** [SERVIR-WA/GALUP#347]
[WS2_M4E1_Shiela.docx](https://github.com/SERVIR-WA/GALUP/files/7634966/WS2_M4E1_Shiela.docx)

**Comment by JuliePeeling** [comment]
Well done, Sheila. You clearly grasped the material outlined in Module 4 and successfully applied it to these exercises. Thank you for your participation! Please be sure to fill out the post-Module survey before you begin the next Module.
