### ISSUE TITLE
Module 4 exercises [replace with your name]

### ISSUE THREAD

**Issue by Wayoe** [SERVIR-WA/GALUP#352]
[WS2_M4E1_ EMMANUEL TETTEH-WAYOE NII.docx](https://github.com/SERVIR-WA/GALUP/files/7635525/WS2_M4E1_.EMMANUEL.TETTEH-WAYOE.NII.docx)

**Comment by JuliePeeling** [comment]
Well done, Emmanuel. You clearly grasped the material outlined in Module 4 and successfully applied it to these exercises. Thank you for your participation! Please be sure to fill out the post-Module survey before you begin the next Module.
