### ISSUE TITLE
Module 4 exercises [Ampadu Boateng Daniel]

### ISSUE THREAD

**Issue by DanielBoateng** [SERVIR-WA/GALUP#354]
[WS2_M4E1_Template.docx](https://github.com/SERVIR-WA/GALUP/files/7635563/WS2_M4E1_Template.docx)

**Comment by JuliePeeling** [comment]
Well done, Daniel You clearly grasped the material outlined in Module 4 and successfully applied it to these exercises. Thank you for your participation! Please be sure to fill out the post-Module survey before you begin the next Module.
