### ISSUE TITLE
Module 4 Afenya David Kweku

### ISSUE THREAD

**Issue by AfenyaDavidKweku** [SERVIR-WA/GALUP#359]
[WS2_M4E1_Template.docx](https://github.com/SERVIR-WA/GALUP/files/7641650/WS2_M4E1_Template.docx)

**Comment by JuliePeeling** [comment]
Well done, Afenya. You clearly grasped the material outlined in Module 4 and successfully applied it to these exercises. Thank you for your participation! Please be sure to fill out the post-Module survey before you begin the next Module.
