### ISSUE TITLE
Module 4 exercises [MARVIN AYEH]

### ISSUE THREAD

**Issue by Marvesc** [SERVIR-WA/GALUP#360]
[WS2_M4E1_Template.docx](https://github.com/SERVIR-WA/GALUP/files/7642218/WS2_M4E1_Template.docx)

**Comment by JuliePeeling** [comment]
Well done, Marvin. You clearly grasped the material outlined in Module 4 and successfully applied it to these exercises. Thank you for your participation! Please be sure to fill out the post-Module survey before you begin the next Module.
