### ISSUE TITLE
Module 4 exercises [replace with your name]

### ISSUE THREAD

**Issue by Edwina-Anderson** [SERVIR-WA/GALUP#363]
[WS2_M4E1_Template (1).docx](https://github.com/SERVIR-WA/GALUP/files/7642771/WS2_M4E1_Template.1.docx)

**Comment by JuliePeeling** [comment]
Well done, Edwina. You clearly grasped the material outlined in Module 4 and successfully applied it to these exercises. Thank you for your participation! Please be sure to fill out the post-Module survey before you begin the next Module.
