### ISSUE TITLE
Patrick

### ISSUE THREAD

**Issue by patrick0502** [SERVIR-WA/GALUP#37]
[Population Map for Assignment 1_Patrick.pdf](https://github.com/SERVIR-WA/GALUP/files/6630926/Population.Map.for.Assignment.1_Patrick.pdf)
[Population Density Map for Assignment 2_Patrick.pdf](https://github.com/SERVIR-WA/GALUP/files/6630927/Population.Density.Map.for.Assignment.2_Patrick.pdf)
[Population Density Map for Assignment 2_Patrick.pdf](https://github.com/SERVIR-WA/GALUP/files/6630964/Population.Density.Map.for.Assignment.2_Patrick.pdf)
[Population Map for Assignment 1_Patrick.pdf](https://github.com/SERVIR-WA/GALUP/files/6630966/Population.Map.for.Assignment.1_Patrick.pdf)

1. Please "drag & drop" exercise 1 pdf file below.

2. Please "drag & drop" exercise 2 pdf file below.

3. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.

4. If you haven't done so, please go back to Module 1 and make sure to take
   the post-training survey. Participating in surveys is required for receiving
   the "GALUP Certificate" by the University of Florida.

**Comment by JuliePeeling** [comment]
Well done, Patrick. You clearly grasped the material outlined in Module 1 and successfully applied it to these exercises. Thank you for your participation! Please be sure to fill out the post-Module survey before you begin the next Module.

**Comment by patrick0502** [comment]
thanks.
please Module 2 is not activated in my GitHub account for me to start.
can you help?



………..

Pln. Patrick Apraku (MGIP, MISoCaRP, MeRSA)

Ag. Director, Standards and Compliance


Land Use and Spatial Planning Authority (LUSPA)

Head Office

P. O. Box MB61

Ministries - Accra




*  The Information in this message and/or attachments is meant solely for the attention and use of the named addresse(s) and may be confidential. If you are not the intended recipient, please you are hereby notified that you have received this transmittal in error and that any use of it is prohibited. In such a case, please delete this message and notify the sender.




















________________________________

**Comment by JuliePeeling** [comment]
Hi Patrick,

Module 2 is still in the process of being edited by the creators of this training, but we will be sure to let all participants know when it is available and ready for use!

Thank you for your patience.

**Comment by patrick0502** [comment]
Thanks Julie

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
