### ISSUE TITLE
Module 4 exercise[YAKUBU HUZIEMATA]

### ISSUE THREAD

**Issue by Huzei09** [SERVIR-WA/GALUP#372]
[WS2_M4E1_ YAKUBU HUZIEMATA.docx](https://github.com/SERVIR-WA/GALUP/files/7652325/WS2_M4E1_.YAKUBU.HUZIEMATA.docx)

**Comment by JuliePeeling** [comment]
Well done, Huziemata. You clearly grasped the material outlined in Module 4 and successfully applied it to these exercises. Thank you for your participation! Please be sure to fill out the post-Module survey before you begin the next Module.
