### ISSUE TITLE
Module 4 exercises Manan Salam

### ISSUE THREAD

**Issue by Manansalam** [SERVIR-WA/GALUP#380]
[classification assignment 2.docx](https://github.com/SERVIR-WA/GALUP/files/7655378/classification.assignment.2.docx)

**Comment by JuliePeeling** [comment]
Well done, Mananu. You clearly grasped the material outlined in Module 4 and successfully applied it to these exercises. Thank you for your participation! Please be sure to fill out the post-Module survey before you begin the next Module.

**Comment by Manansalam** [comment]
Sir please l did not see my name on the graduation list

**Comment by JuliePeeling** [comment]
Dear Mananu,

We congratulate you on your hard work on this workshop and greatly appreciate your participation! We are currently missing the Module 4 survey from you, which is required for workshop completion. However, if you have submitted this and our system has not refreshed to take this into account yet, we will check that immediately. We apologize that we were not able to include your certificate in the meeting, but once we have your survey we will create a hard copy of the certificate and send it to you.

Best,
Julie

**Comment by JuliePeeling** [comment]
We have received your survey! Thank you for your patience and hard work on the exercises in this workshop, and congratulations on your accomplishments.

**Comment by JuliePeeling** [comment]
Dear Mananu,

We thought we had received your survey, but upon further inspection, we could not see it in our records. Please submit this at your earliest convenience. Thanks!

Best,
Julie
