### ISSUE TITLE
Module 1 exercises []

### ISSUE THREAD

**Issue by ameley1** [SERVIR-WA/GALUP#382]
1. Please "drag & drop" exercise 1 file below.

[WS2_M1E1_Submission_Francisca.docx](https://github.com/SERVIR-WA/GALUP/files/7656155/WS2_M1E1_Submission_Francisca.docx)

3. If you haven't done so, please go back to Module 1 and make sure to take
   the post-training survey.

**Comment by JuliePeeling** [comment]
Thank you for your successful submission to the practice exercise! Please be sure to fill out the post-Module survey.
