### ISSUE TITLE
Module 1 exercises [Ebenezer Ntsifu;l]

### ISSUE THREAD

**Issue by EbenezerN** [SERVIR-WA/GALUP#387]
![M1E2_Ebenezer Ntsiful](https://user-images.githubusercontent.com/13640502/144757537-88bbc0ba-ee3a-402f-8090-262aa42e15ac.png)
![M1E1_Ebenezer Ntsiful](https://user-images.githubusercontent.com/13640502/144757540-84251c2f-290c-4253-b319-d9c7f79c2cce.png)

**Comment by JuliePeeling** [comment]
Thank you for your successful submission to the practice exercise! Please be sure to fill out the post-Module survey.
