### ISSUE TITLE
SEYRAM KWAME BOTCHIE

### ISSUE THREAD

**Issue by GitMalachi** [SERVIR-WA/GALUP#388]
[MODULE 4 ASSIGNMENT SKB.docx](https://github.com/SERVIR-WA/GALUP/files/7656503/MODULE.4.ASSIGNMENT.SKB.docx)

**Comment by JuliePeeling** [comment]
Well done, Seyram. You clearly grasped the material outlined in Module 4 and successfully applied it to these exercises. Thank you for your participation! Please be sure to fill out the post-Module survey before you begin the next Module.
