### ISSUE TITLE
Workshop 3 exercise [Silas Achidago]

### ISSUE THREAD

**Issue by Achidago** [SERVIR-WA/GALUP#409]
1. Please "drag & drop" the result map of your exercise file below.
[IDU Output.pdf](https://github.com/SERVIR-WA/GALUP/files/8636592/IDU.Output.pdf)

2. Please "drag & drop" the zip file of the IDU shapefile for AAC district.
[Final_Merged_IDU.zip](https://github.com/SERVIR-WA/GALUP/files/8636596/Final_Merged_IDU.zip)

3. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.

4. If you haven't done so, please go back to the module and make sure to take
   the post-training survey. Participating in surveys is required for receiving
   the "GALUP Certificate" by the University of Florida.

**Comment by eidealex** [comment]
Well done, Silas. You clearly grasped the material outlined in Workshop 3 and successfully applied it to this exercise. Thank you for your participation! Please be sure to fill out the post-Module survey.
