### ISSUE TITLE
Workshop 3 exercise [MARVIN AYEH]

### ISSUE THREAD

**Issue by Marvesc** [SERVIR-WA/GALUP#411]
1. Please "drag & drop" the result map of your exercise file below.
[AAX_IDU_M.A.pdf](https://github.com/SERVIR-WA/GALUP/files/8708067/AAX_IDU_M.A.pdf)

2. Please "drag & drop" the 
zip file of the ID
[MARVIN_AYEH_AAC.IDU.zip](https://github.com/SERVIR-WA/GALUP/files/8708070/MARVIN_AYEH_AAC.IDU.zip)
U shapefile for AAC district.

3. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.

4. If you haven't done so, please go back to the module and make sure to take
   the post-training survey. Participating in surveys is required for receiving
   the "GALUP Certificate" by the University of Florida.

**Comment by eidealex** [comment]
Well done, Marvin. You clearly grasped the material outlined in Workshop 3 and successfully applied it to this exercise. Thank you for your participation! Please be sure to fill out the post-Module survey.
