### ISSUE TITLE
Workshop 3 exercise [Beatrice Owusu-Appiah]

### ISSUE THREAD

**Issue by AdjoaOwusua** [SERVIR-WA/GALUP#422]
1. Please "drag & drop" the result map of your exercise file below.
![Uploading IDU_Output_Beatrice Owusu-Appiah.jpg…]

2. Please "drag & drop" the zip file of the IDU shapefile for AAC district.
[IDU_Output_Beatrice Owusu-Appiah.zip](https://github.com/SERVIR-WA/GALUP/files/8924479/IDU_Output_Beatrice.Owusu-Appiah.zip)

3. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.

4. If you haven't done so, please go back to the module and make sure to take
   the post-training survey. Participating in surveys is required for receiving
   the "GALUP Certificate" by the University of Florida.

**Comment by eidealex** [comment]
Well done, Beatrice. You clearly grasped the material outlined in Workshop 3 and successfully applied it to the exercise. Thank you for your participation! Please be sure to fill out the post-Module survey.
