### ISSUE TITLE
Workshop 3 exercise [HUZIEMATA YAKUBU]

### ISSUE THREAD

**Issue by Huzei09** [SERVIR-WA/GALUP#423]
1. Please "
![IDU_Output_HUZIEMATA YAKUBU](https://user-images.githubusercontent.com/93486140/174298723-eb80042d-d40a-42e6-9e75-63d668dc7055.jpg)
drag & drop" the result map of your exercise file below.

2. Please "
[IDU_Output_HUZIEMATA YAKUBU.zip](https://github.com/SERVIR-WA/GALUP/files/8927455/IDU_Output_HUZIEMATA.YAKUBU.zip)
drag & drop" the zip file of the IDU shapefile for AAC district.

3. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.

4. If you haven't done so, please go back to the module and make sure to take
   the post-training survey. Participating in surveys is required for receiving
   the "GALUP Certificate" by the University of Florida.

**Comment by eidealex** [comment]
Well done, Huziemata. You clearly grasped the material outlined in Workshop 3 and successfully applied it to the exercise. Thank you for your participation! Please be sure to fill out the post-Module survey.
