### ISSUE TITLE
Workshop 4 exercise 0 [Mohammed Munzamil]

### ISSUE THREAD

**Issue by mmunzamil** [SERVIR-WA/GALUP#427]
1. Please "drag & drop" exercise 0 file below.

[MM Workshop 4 exercise 0.docx](https://github.com/SERVIR-WA/GALUP/files/9999675/MM.Workshop.4.exercise.0.docx)

2. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.

**Comment by Achidago** [comment]
Great observation and analysis Munzamil! Good job
