### ISSUE TITLE
Workshop 4 exercise 0 [MARVIN AYEH]

### ISSUE THREAD

**Issue by Marvesc** [SERVIR-WA/GALUP#428]
1. Please "drag & drop" exercise 0 file below.
[M.A_W4M0.docx](https://github.com/SERVIR-WA/GALUP/files/10008207/M.A_W4M0.docx)

2. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.

**Comment by JuliePeeling** [comment]
Great work! Nice observation.
