### ISSUE TITLE
Workshop 4 exercise 0 [Samuel Fianyo-Adovor]

### ISSUE THREAD

**Issue by Ejw1995** [SERVIR-WA/GALUP#432]
1. Please "drag & drop" exercise 0 file below.

2. Please UPDATE TH
[Module 0 Exercise - SAMUEL FIANYO-ADOVOR.docx](https://github.com/SERVIR-WA/GALUP/files/10012763/Module.0.Exercise.-.SAMUEL.FIANYO-ADOVOR.docx)
E TITLE of this "Issue" in the title bar above with your name.

**Comment by JuliePeeling** [comment]
Excellent observations!
