### ISSUE TITLE
Workshop 4 exercise 0 [Edith Kwablah]

### ISSUE THREAD

**Issue by edythneska** [SERVIR-WA/GALUP#438]
1. Please "drag & drop" exercise 0 file below.

2. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.
[Edith Kwablah_study and compare assignment.docx](https://github.com/SERVIR-WA/GALUP/files/10014466/Edith.Kwablah_study.and.compare.assignment.docx)

**Comment by Achidago** [comment]
Great analysis Edith! Good job
