### ISSUE TITLE
Workshop 4 exercise 0 [BASHARA AHMED ABUBAKARI]

### ISSUE THREAD

**Issue by Bashmeludu** [SERVIR-WA/GALUP#441]
1. Please "drag & drop" exercise 0 file below.

2. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.
[W4M0.docx](https://github.com/SERVIR-WA/GALUP/files/10015689/W4M0.docx)

**Comment by Achidago** [comment]
Excellent observation!
