### ISSUE TITLE
Workshop 4 exercise 0 [Ronald Reagan Gyimah]

### ISSUE THREAD

**Issue by reygyimah** [SERVIR-WA/GALUP#446]
There is no much difference due to the presence of cloud cover in the region (western region of Ghana). However, the later date (2020-2021) image has much more cloud cover that the former (2004-2005).
<img width="1440" alt="Screenshot 2022-11-16 at 1 25 53 PM" src="https://user-images.githubusercontent.com/93355003/202197710-02b9ad05-1a9e-4610-a794-15de749f3964.png">

<img width="1440" alt="Screenshot 2022-11-16 at 1 26 33 PM" src="https://user-images.githubusercontent.com/93355003/202196401-da47da16-cf75-4ae1-a9bc-063969bca3bc.png">

**Comment by JuliePeeling** [comment]
Great observations!
