### ISSUE TITLE
Module 1 Exercise 1 [Enaruvbe]

### ISSUE THREAD

**Issue by enaruvbe** [SERVIR-WA/GALUP#449]
1. Please "drag & drop" exercise 1 file below.

2. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.
[Exercise 1.docx](https://github.com/SERVIR-WA/GALUP/files/10022900/Exercise.1.docx)

**Comment by JuliePeeling** [comment]
Great graph and interpretation!
