### ISSUE TITLE
Module 2 exercises [Julie Peeling]

### ISSUE THREAD

**Issue by JuliePeeling** [SERVIR-WA/GALUP#45]
1. Please "drag & drop" exercise 1 pdf file below.
[Module2Exercise1.pdf](https://github.com/SERVIR-WA/GALUP/files/6639639/Module2Exercise1.pdf)

2. Please "drag & drop" exercise 2 pdf file below.
[Module2Exercise2.pdf](https://github.com/SERVIR-WA/GALUP/files/6639643/Module2Exercise2.pdf)

3. Please "drag & drop" exercise 3 pdf file below.
[Module2Exercise3.pdf](https://github.com/SERVIR-WA/GALUP/files/6639644/Module2Exercise3.pdf)

4. Please "drag & drop" exercise 4 pdf file below.
[Module2Exercise4.pdf](https://github.com/SERVIR-WA/GALUP/files/6639645/Module2Exercise4.pdf)

5. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.

6. If you haven't done so, please go back to Module 2 and make sure to take
   the post-training survey. Participating in surveys is required for receiving
   the "GALUP Certificate" by the University of Florida.

**Comment by JuliePeeling** [comment]
The original submissions did not have the correct ESRI background, apologies.
Exercise 1
[Module2Exercise1.pdf](https://github.com/SERVIR-WA/GALUP/files/6639699/Module2Exercise1.pdf)
Exercise 2
[Module2Exercise2.pdf](https://github.com/SERVIR-WA/GALUP/files/6639692/Module2Exercise2.pdf)
Exercise 3
[Module2Exercise3.pdf](https://github.com/SERVIR-WA/GALUP/files/6639693/Module2Exercise3.pdf)
Exercise 4
[Module2Exercise4.pdf](https://github.com/SERVIR-WA/GALUP/files/6639694/Module2Exercise4.pdf)

**Comment by chjch** [comment]
Thank you Julie. Perfect!
