### ISSUE TITLE
Alex Opoku Boateng

### ISSUE THREAD

**Issue by OseiAgyekum** [SERVIR-WA/GALUP#452]
1. Please "drag & drop" exercise 1 file below.

2. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.

[Module1-exercise1.docx](https://github.com/SERVIR-WA/GALUP/files/10023004/Module1-exercise1.docx)

**Comment by JuliePeeling** [comment]
Excellent analysis of the graph!
