### ISSUE TITLE
Module 1 Exercise 1 Afenya David Kweku

### ISSUE THREAD

**Issue by AfenyaDavidKweku** [SERVIR-WA/GALUP#454]
1. Please "drag & drop" exercise 1 file below.

2. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.
[Module 1 Exercise 1.docx](https://github.com/SERVIR-WA/GALUP/files/10023014/Module.1.Exercise.1.docx)

**Comment by JuliePeeling** [comment]
Great work on the graph and interpretation!
