### ISSUE TITLE
Workshop 4 exercise 0 [Pascal Cleland]

### ISSUE THREAD

**Issue by pascalvictor** [SERVIR-WA/GALUP#455]
[NDVI slopes review.docx](https://github.com/SERVIR-WA/GALUP/files/10023056/NDVI.slopes.review.docx)

1. Please "drag & drop" exercise 0 file below.

2. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.

**Comment by JuliePeeling** [comment]
Great analysis of the graphs!
