### ISSUE TITLE
Module 1 Exercise 1 [NARTEY ERIC ]

### ISSUE THREAD

**Issue by Kikayeric** [SERVIR-WA/GALUP#459]
1. Please "drag & drop" exercise 1 file below.

2. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.
[EXERCISE 1.docx](https://github.com/SERVIR-WA/GALUP/files/10023133/EXERCISE.1.docx)

**Comment by JuliePeeling** [comment]
Excellent graph and analysis!
