### ISSUE TITLE
Module 1 Exercise 1 [Edith Kwabalh]

### ISSUE THREAD

**Issue by edythneska** [SERVIR-WA/GALUP#460]
1. Please "drag & drop" exercise 1 file below.
[Edith Kwablah_module 1_Ex1.docx](https://github.com/SERVIR-WA/GALUP/files/10023114/Edith.Kwablah_module.1_Ex1.docx)

2. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.

**Comment by JuliePeeling** [comment]
Nice work on the graph and observations!
