### ISSUE TITLE
Workshop 4 exercise 0 [HUZIEMATA YAKUBU]

### ISSUE THREAD

**Issue by Huzei09** [SERVIR-WA/GALUP#466]
1. Please "drag & drop" exercise 0 file below.
[Huziemata Yakubu_exercise 0.docx](https://github.com/SERVIR-WA/GALUP/files/10023426/Huziemata.Yakubu_exercise.0.docx)

3. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.

**Comment by JuliePeeling** [comment]
Excellent work!
