### ISSUE TITLE
Module 1 Exercise 1 [Celestina Deku]

### ISSUE THREAD

**Issue by Awusi** [SERVIR-WA/GALUP#468]
1. Please "
[Workshop 4 Module 1 Exercise 1.docx](https://github.com/SERVIR-WA/GALUP/files/10024182/Workshop.4.Module.1.Exercise.1.docx)
drag & drop" exercise 1 file below.

2. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.

**Comment by JuliePeeling** [comment]
Great graph and observations!
