### ISSUE TITLE
Module 1 Exercise 2 [Edith Kwablah]

### ISSUE THREAD

**Issue by edythneska** [SERVIR-WA/GALUP#472]
1. Please "drag & drop" exercise 2 file below.

2. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.
[Edith Kwablah_module 1_Ex2.docx](https://github.com/SERVIR-WA/GALUP/files/10031203/Edith.Kwablah_module.1_Ex2.docx)

**Comment by JuliePeeling** [comment]
Great observations on the graphs!
