### ISSUE TITLE
Edwina Anderson

### ISSUE THREAD

**Issue by Edwina-Anderson** [SERVIR-WA/GALUP#474]
1. Please "drag & drop" exercise 1 excel file below.
[GALUP TRAINING MODULE 4.docx](https://github.com/SERVI
[EDWINA ANDERSON -GALUP TRAINING MODULE 4.docx](https://github.com/SERVIR-WA/GALUP/files/10031219/EDWINA.ANDERSON.-GALUP.TRAINING.MODULE.4.docx)
R-WA/GALUP/files/10031208/GALUP.TRAINING.MODULE.4.docx)

2. Please "drag & drop" exercise 2 excel file below.

3. Please "drag & drop" exercise 3 pdf file below.

4. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.

5. If you haven't done so, please go back to Module 4 and make sure to take
   the post-training survey. Participating in surveys is required for receiving
   the "GALUP Certificate" by the University of Florida.

**Comment by JuliePeeling** [comment]
Excellent graphs and analysis!
