### ISSUE TITLE
Module 1 Exercise 2 [Ernest Dusu Xoese]

### ISSUE THREAD

**Issue by Ernest-Dusu** [SERVIR-WA/GALUP#476]
1. Please "drag & drop" exercise 2 file below.
[Ernest Dusu exercise 2.docx](https://github.com/SERVIR-WA/GALUP/files/10031248/Ernest.Dusu.exercise.2.docx)

3. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.

**Comment by JuliePeeling** [comment]
Nice interpretation of the graphs!
