### ISSUE TITLE
Module 1 Exercise 2 [Pascal Cleland]

### ISSUE THREAD

**Issue by pascalvictor** [SERVIR-WA/GALUP#478]
[Linear trends.docx](https://github.com/SERVIR-WA/GALUP/files/10031314/Linear.trends.docx)
1. Please "drag & drop" exercise 2 file below.

2. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.

**Comment by JuliePeeling** [comment]
Excellent observations on the graphs!
