### ISSUE TITLE
Module 1 Exercise 2 on Time Series [Bako]

### ISSUE THREAD

**Issue by BAKOMAMANE** [SERVIR-WA/GALUP#483]
1. Please "drag & drop" exercise 2 file below.
![Rainfall_Map](https://user-images.githubusercontent.com/13468519/202444539-baa5f73d-cf7b-4ca1-8396-35e6ba4a2c0e.PNG)
![ee-chart_Temp_bm](https://user-images.githubusercontent.com/13468519/202444565-7c73641b-a9d3-4278-a055-d45575688658.png)
![ee-chart_rain_bm](https://user-images.githubusercontent.com/13468519/202444587-26953cda-0163-4b4d-a80e-fd0e30e6f490.png)

2. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.

**Comment by JuliePeeling** [comment]
Excellent graphs!
