### ISSUE TITLE
Module 1 Exercise 2 [Edwina Anderson]

### ISSUE THREAD

**Issue by Edwina-Anderson** [SERVIR-WA/GALUP#484]
1. Please "drag & drop" exercise 2 file below.

2. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.
[EDWINA ANDERSON -GALUP TRAINING MODULE 4.docx](https://github.com/SERVIR-WA/GALUP/files/10031398/EDWINA.ANDERSON.-GALUP.TRAINING.MODULE.4.docx)

**Comment by JuliePeeling** [comment]
Excellent descriptions of the graphs!
