### ISSUE TITLE
Module 1 Exercise 2 [Kuulara Paapa Williams]

### ISSUE THREAD

**Issue by kuularapaapawilliams** [SERVIR-WA/GALUP#485]
1. Please "drag & drop" exercise 2 file below.

2. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.
[EXERCISE 2.docx](https://github.com/SERVIR-WA/GALUP/files/10031409/EXERCISE.2.docx)

**Comment by JuliePeeling** [comment]
Great work!
