### ISSUE TITLE
Module 1 Exercise 2 [NARTEY ERIC]

### ISSUE THREAD

**Issue by Kikayeric** [SERVIR-WA/GALUP#486]
1. Please "drag & drop" exercise 2 file below.

2. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.
[Exercise.docx](https://github.com/SERVIR-WA/GALUP/files/10031402/Exercise.docx)

**Comment by JuliePeeling** [comment]
Nice observations on the graphs!
