### ISSUE TITLE
Pauline Ornela Megne Choudja

### ISSUE THREAD

**Issue by MEGNEOrnela** [SERVIR-WA/GALUP#488]
1. Please "drag & drop" exercise 2 file below.
[Exercise 2.pdf](https://github.com/SERVIR-WA/GALUP/files/10031537/Exercise.2.pdf)

2. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.

**Comment by JuliePeeling** [comment]
Excellent work and observations!
