### ISSUE TITLE
Module 2 exercises [Sheila A. N Humphrey - Ackumey]

### ISSUE THREAD

**Issue by Sheila6868** [SERVIR-WA/GALUP#49]
1. Please "drag & drop" exercise 1 pdf file below.
[M2E1- Sheila.pdf](https://github.com/SERVIR-WA/GALUP/files/6649068/M2E1-.Sheila.pdf)

2. Please "drag & drop" exercise 2 pdf file below.
[Exercise 2 -Sheila - Copy.pdf](https://github.com/SERVIR-WA/GALUP/files/6676588/Exercise.2.-Sheila.-.Copy.pdf)

3. Please "drag & drop" exercise 3 pdf file below.
[M2E3 - Sheila.pdf](https://github.com/SERVIR-WA/GALUP/files/6649070/M2E3.-.Sheila.pdf)

4. Please "drag & drop" exercise 4 pdf file below.
[M2E4 - Sheila.pdf](https://github.com/SERVIR-WA/GALUP/files/6649072/M2E4.-.Sheila.pdf)

5. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.

6. If you haven't done so, please go back to Module 2 and make sure to take
   the post-training survey. Participating in surveys is required for receiving
   the "GALUP Certificate" by the University of Florida.

**Comment by muribasterra** [comment]
Well done, Sheila. You clearly grasped the material outlined in Module 2 and successfully applied it to these exercises. There was a minor issue with your symbology for Exercise 2, but this can be fixed by navigating to the Symbology tab under layer properties and changing the Mode from "Equal Count (Quantile)" to "Natural Jenks." Please reapply symbology using Natural Jenks and resubmit Exercise 2 above.

Great job otherwise, and thank you for your participation!

**Comment by Sheila6868** [comment]
Thanks for the feedback. As directed, I have edited and resubmitted Exercise 2. Thanks

**Comment by Sheila6868** [comment]
> Well done, Sheila. You clearly grasped the material outlined in Module 2 and successfully applied it to these exercises. There was a minor issue with your symbology for Exercise 2, but this can be fixed by navigating to the Symbology tab under layer properties and changing the Mode from "Equal Count (Quantile)" to "Natural Jenks." Please reapply symbology using Natural Jenks and resubmit Exercise 2 above.
> 
> Great job otherwise, and thank you for your participation!

**Comment by Sheila6868** [comment]
Thanks for the feedback. I have edited and resubmitted exercise 2. Thanks 


Sent from Yahoo Mail for iPhone


On Thursday, June 17, 2021, 9:22 PM, muribasterra ***@***.***> wrote:




Well done, Sheila. You clearly grasped the material outlined in Module 2 and successfully applied it to these exercises. There was a minor issue with your symbology for Exercise 2, but this can be fixed by navigating to the Symbology tab under layer properties and changing the Mode from "Equal Count (Quantile)" to "Natural Jenks." Please reapply symbology using Natural Jenks and resubmit Exercise 2 above.

Great job otherwise, and thank you for your participation!
