### ISSUE TITLE
Workshop 4 exercise 0 [Deborah Alaigba]

### ISSUE THREAD

**Issue by Debbiebless** [SERVIR-WA/GALUP#494]
1. Please "drag & drop" exercise 0 file below.

2. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.
[Alaigba- Exercise 0.docx](https://github.com/SERVIR-WA/GALUP/files/10032231/Alaigba-.Exercise.0.docx)

**Comment by JuliePeeling** [comment]
Great observations!
