### ISSUE TITLE
Module 2 Exercise 4 [BAKO]

### ISSUE THREAD

**Issue by BAKOMAMANE** [SERVIR-WA/GALUP#496]
1. Please "drag & drop" exercise 4 file below.
![Flooding_2021](https://user-images.githubusercontent.com/13468519/202495953-72e2a59e-dcbb-4ad4-b13d-5528d07b1eec.PNG)

![Flooding_2020](https://user-images.githubusercontent.com/13468519/202495968-fd656a7c-065e-457e-b835-7a5cdc9efbe7.PNG)

2. Please UPDATE THE TITLE of this "Issue" in the title b
 I compared 2 years 2020 one fo the historical flooding year with 2021 which is a normal one. the Conclusion is 
Flood extent 2020 : 186677 vs 2021: 169732
Exposed Population : 396659 vs 346213
Affected Cropland : 32048 vs 30276
Urban area : 8094 vs 5504

**Comment by JuliePeeling** [comment]
Nice comparisons and observations!
