### ISSUE TITLE
Module 2 Exercise 3 [Alex Opoku Boateng]

### ISSUE THREAD

**Issue by opokuboateng** [SERVIR-WA/GALUP#498]
1. Please "drag & drop" exercise 3 file below.

2. Please UPDATE THE TITLE of thi
[Flood damage analysis map.docx](https://github.com/SERVIR-WA/GALUP/files/10033482/Flood.damage.analysis.map.docx)
s "Issue" in the title bar above with your name.

**Comment by JuliePeeling** [comment]
Great work!
