### ISSUE TITLE
Module 2 Exercise 3 [Edith Kwablah]

### ISSUE THREAD

**Issue by edythneska** [SERVIR-WA/GALUP#500]
1. Please "drag & drop" exercise 3 file below.

2. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.
[Edith Kwablah_module 2_Ex3.docx](https://github.com/SERVIR-WA/GALUP/files/10033623/Edith.Kwablah_module.2_Ex3.docx)

**Comment by JuliePeeling** [comment]
Excellent analysis!
