### ISSUE TITLE
Workshop Exercise 2 [Pascal Cleland]

### ISSUE THREAD

**Issue by pascalvictor** [SERVIR-WA/GALUP#505]
[MultiYear land cover change.docx](https://github.com/SERVIR-WA/GALUP/files/10033755/MultiYear.land.cover.change.docx)
1. Please "drag & drop" exercise 4 file below.

2. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.

**Comment by JuliePeeling** [comment]
Excellent work!
