### ISSUE TITLE
Module 2 Exercise 3 [Kuulara Paapa Williams]

### ISSUE THREAD

**Issue by kuularapaapawilliams** [SERVIR-WA/GALUP#507]
1. Please "drag & drop" exercise 3 file below.

2. Please UPDATE THE TITLE of this "Issue" in the title bar above with your nam
[Exercise 3.docx](https://github.com/SERVIR-WA/GALUP/files/10033790/Exercise.3.docx)

**Comment by JuliePeeling** [comment]
Great assessment!
