### ISSUE TITLE
Module 2 Exercise 4 [Edwina Anderson]

### ISSUE THREAD

**Issue by Edwina-Anderson** [SERVIR-WA/GALUP#511]
1. Please "drag & drop" exercise 4 file below.

2. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.
[GALUP- Excercise 4.docx](https://github.com/SERVIR-WA/GALUP/files/10033838/GALUP-.Excercise.4.docx)

**Comment by JuliePeeling** [comment]
Great analysis!
