### ISSUE TITLE
Workshop 4xercise 2 [Enaruvbe]

### ISSUE THREAD

**Issue by enaruvbe** [SERVIR-WA/GALUP#528]
1. Please "drag & drop" exercise 3 file below.

2. Please UPDATE TH
[Mod2_Ex_4.docx](https://github.com/SERVIR-WA/GALUP/files/10042780/Mod2_Ex_4.docx)

This map shows the area around the city of Sokoto in Sokoto State, northern Nigeria. A large part of the area can be potentially flooded with a large area of cropland affected.

**Comment by JuliePeeling** [comment]
Excellent analysis!
