### ISSUE TITLE
Mmoloki Ntema

### ISSUE THREAD

**Issue by Mmolokintema** [SERVIR-WA/GALUP#544]
1. Please "drag & drop" exercise 1 pdf file below.
[Botswana Population by District in 2022.pdf](https://github.com/SERVIR-WA/GALUP/files/13310543/Botswana.Population.by.District.in.2022.pdf)

2. Please "drag & drop" exercise 2 p
[Botswana Population Density by District in 2022.pdf](https://github.com/SERVIR-WA/GALUP/files/13310546/Botswana.Population.Density.by.District.in.2022.pdf)
df file below.

3. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.

4. If you haven't done so, please go back to Module 1 and make sure to take
   the post-training survey. Participating in surveys is required for receiving
   the "GALUP Certificate" by the University of Florida.

**Comment by chjch** [comment]
Well done, Mmoloki. You clearly grasped the material outlined in Module 1 and successfully applied it to these exercises. Thank you for your participation!
