### ISSUE TITLE
Module 1 exercises omphemetse okaile

### ISSUE THREAD

**Issue by ookaile** [SERVIR-WA/GALUP#546]
1. Please "drag & drop" exercise 1 pdf file be
[Botswana Population by District in 2022.pdf](https://github.com/SERVIR-WA/GALUP/files/13310675/Botswana.Population.by.District.in.2022.pdf)
low.

2. Please "drag & drop" exercise 2 pdf file 
[Botswana Population Density by District in 2022.pdf](https://github.com/SERVIR-WA/GALUP/files/13310679/Botswana.Population.Density.by.District.in.2022.pdf)
below.

3. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.

4. If you haven't done so, please go back to Module 1 and make sure to take
   the post-training survey. Participating in surveys is required for receiving
   the "GALUP Certificate" by the University of Florida.

**Comment by chjch** [comment]
Well done, Okaile. You clearly grasped the material outlined in Module 1 and successfully applied it to these exercises. Thank you for your participation!
