### ISSUE TITLE
KEDISALETSE SELUME

### ISSUE THREAD

**Issue by Kedisaletse** [SERVIR-WA/GALUP#547]
[EXERCISE 1 MAP.pdf](https://github.com/SERVIR-WA/GALUP/files/13310844/EXERCISE.1.MAP.pdf)
1. Please "drag & drop" exercise 1 pdf file below.

2. Please "drag & drop" exercise 2 pdf file below.

3. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.

4. If you haven't done so, please go back to Module 1 and make sure to take
   the post-training survey. Participating in surveys is required for receiving
   the "GALUP Certificate" by the University of Florida.
[EXERCISE  2.pdf](https://github.com/SERVIR-WA/GALUP/files/13310853/EXERCISE.2.pdf)

**Comment by Kedisaletse** [comment]
EXERCISE SUBMISSION

**Comment by chjch** [comment]
Well done, Kedi. You clearly grasped the material outlined in Module 1 and successfully applied it to these exercises. Thank you for your participation!
