### ISSUE TITLE
Theetso Masilomangwe

### ISSUE THREAD

**Issue by theemasi** [SERVIR-WA/GALUP#549]
1
[Exercise_1.pdf](https://github.com/SERVIR-WA/GALUP/files/13318097/Exercise_1.pdf)
. Please "drag & drop" exercise 1 pdf file below.

2. Please "drag & drop" exercise 2 pdf file below.
[Exercise_2.pdf](https://github.com/SERVIR-WA/GALUP/files/13318098/Exercise_2.pdf)

3. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.

4. If you haven't done so, please go back to Module 1 and make sure to take
   the post-training survey. Participating in surveys is required for receiving
   the "GALUP Certificate" by the University of Florida.

**Comment by chjch** [comment]
Well done, Theetso. You clearly grasped the material outlined in Module 1 and successfully applied it to these exercises. Thank you for your participation!
