### ISSUE TITLE
Module 2 exercises [Ama Agyeiwaa Boadu]

### ISSUE THREAD

**Issue by Amaluspa** [SERVIR-WA/GALUP#55]
[Amaluspa module 2.ass 2.pdf](https://github.com/SERVIR-WA/GALUP/files/6650838/Amaluspa.module.2.ass.2.pdf)
[Amaluspa module 2.ass 3.pdf](https://github.com/SERVIR-WA/GALUP/files/6650839/Amaluspa.module.2.ass.3.pdf)
[Amaluspa module 2.ass 4.pdf](https://github.com/SERVIR-WA/GALUP/files/6650841/Amaluspa.module.2.ass.4.pdf)
[Amaluspa module 2.ass_1.pdf](https://github.com/SERVIR-WA/GALUP/files/6650842/Amaluspa.module.2.ass_1.pdf)

**Comment by muribasterra** [comment]
Well done, Ama. You clearly grasped the material outlined in Module 2 and successfully applied it to these exercises. Thank you for your participation!
