### ISSUE TITLE
Module 1 exercises [Duduetsang K. Paul]

### ISSUE THREAD

**Issue by dkkpaul** [SERVIR-WA/GALUP#550]
1. Please "drag & drop" exercise 1 pdf fil
[Botswana Population By District In 2022.pdf](https://github.com/SERVIR-WA/GALUP/files/13320589/Botswana.Population.By.District.In.2022.pdf)
e below.

2. Please "drag 
[Botswana Population Density by District in 2022.pdf](https://github.com/SERVIR-WA/GALUP/files/13320591/Botswana.Population.Density.by.District.in.2022.pdf)
& drop" exercise 2 pdf file below.

3. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.

4. If you haven't done so, please go back to Module 1 and make sure to take
   the post-training survey. Participating in surveys is required for receiving
   the "GALUP Certificate" by the University of Florida.

**Comment by chjch** [comment]
Well done, Duduetsang. You clearly grasped the material outlined in Module 1 and successfully applied it to these exercises. Thank you for your participation!
