### ISSUE TITLE
BOFELO MOTLHABANE

### ISSUE THREAD

**Issue by Bofelo24** [SERVIR-WA/GALUP#554]
[BW POPULATION DENSITY MAP 2022.pdf](https://github.com/SERVIR-WA/GALUP/files/13340331/BW.POPULATION.DENSITY.MAP.2022.pdf)
[BW POPULATION MAP 2022.pdf](https://github.com/SERVIR-WA/GALUP/files/13340332/BW.POPULATION.MAP.2022.pdf)

**Comment by chjch** [comment]
Well done, Bofelo. You clearly grasped the material outlined in Module 1 and successfully applied it to these exercises. Thank you for your participation! Please make sure to finish the post-module1 survey which you can find at [here](https://servir-wa.github.io/GALUP/html/5_m1.html#exercises-and-post-training-survey).
