### ISSUE TITLE
Module 1 exercises (KHAULANI RAUWE)

### ISSUE THREAD

**Issue by Rauwegis** [SERVIR-WA/GALUP#555]
1. Please "drag & drop" exercise 1 pdf file below.

2. Please "drag & drop" exercise 2 pdf file below.

3. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.
[EXERCISE 1 MAP- RAUWE.pdf](https://github.com/SERVIR-WA/GALUP/files/13341261/EXERCISE.1.MAP-.RAUWE.pdf)

4. If you haven't done so, please go back to Module 1 and make sure to take
   the post-training survey. Participating in surveys is required for receiving
   the "GALUP Certificate" by the University of Florida.
[EXERCISE 2 MAP RAUWE.pdf](https://github.com/SERVIR-WA/GALUP/files/13341328/EXERCISE.2.MAP.RAUWE.pdf)

**Comment by chjch** [comment]
Well done, Khaulani. You clearly grasped the material outlined in Module 1 and successfully applied it to these exercises. Thank you for your participation! Please make sure to finish the post-module1 survey which you can find at [here](https://servir-wa.github.io/GALUP/html/5_m1.html#exercises-and-post-training-survey).
