### ISSUE TITLE
Module 1 exercises [Goabaone Ntloedibe]

### ISSUE THREAD

**Issue by GoabaNtlo** [SERVIR-WA/GALUP#556]
1. Please "drag & drop" exercise 1 pdf file below.

[MAP EXERCISE 1 NTLO.pdf](https://github.com/SERVIR-WA/GALUP/files/13341522/MAP.EXERCISE.1.NTLO.pdf)

2. Please "drag & drop" exercise 2 pdf file below.
[EXERCISE 2 NTLO MAP.pdf](https://github.com/SERVIR-WA/GALUP/files/13341558/EXERCISE.2.NTLO.MAP.pdf)

3. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.

4. If you haven't done so, please go back to Module 1 and make sure to take
   the post-training survey. Participating in surveys is required for receiving
   the "GALUP Certificate" by the University of Florida.

**Comment by chjch** [comment]
Well done, Goabaone. You clearly grasped the material outlined in Module 1 and successfully applied it to these exercises. Thank you for your participation! Please make sure to finish the post-module1 survey which you can find at [here](https://servir-wa.github.io/GALUP/html/5_m1.html#exercises-and-post-training-survey).
