### ISSUE TITLE
Module 1 exercises [replace with your name]

### ISSUE THREAD

**Issue by MMATREE** [SERVIR-WA/GALUP#559]
[module 1 o.moleta.pdf](https://github.com/SERVIR-WA/GALUP/files/13346459/module.1.o.moleta.pdf)

[POP_DEN.pdf](https://github.com/SERVIR-WA/GALUP/files/13346460/POP_DEN.pdf)

**Comment by chjch** [comment]
Thank you for your participation. Can you please provide your name and organization?

**Comment by chjch** [comment]
Well done, Onneetse. You clearly grasped the material outlined in Module 1 and successfully applied it to these exercises. Thank you for your participation! If you haven't completed the post-module1 survey, please do so [here](https://ufl.qualtrics.com/jfe/form/SV_7QjV59cEgOtfwrQ).
