### ISSUE TITLE
Olefile V. Maikaelelo

### ISSUE THREAD

**Issue by omaikaelelo** [SERVIR-WA/GALUP#563]
Exercise 2
[Botswana_2.pdf](https://github.com/SERVIR-WA/GALUP/files/13348041/Botswana_2.pdf)

**Comment by chjch** [comment]
Well done, Olefile. You clearly grasped the material outlined in Module 1 and successfully applied it to these exercises. Thank you for your participation! Please make sure to finish the post-module1 survey which you can find at [here](https://servir-wa.github.io/GALUP/html/5_m1.html#exercises-and-post-training-survey).
