### ISSUE TITLE
Module 1 exercises [KESEGO MOTSWASELE

### ISSUE THREAD

**Issue by CASSIEMOTS** [SERVIR-WA/GALUP#569]
1. Please "drag & drop" exercise 1 pdf file below.

2. Please "drag & drop" exercise 2 pdf file below.

3. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.

4. If you haven't done so, please go back to Module 1 and make sure to take
   the post-training survey. Participating in surveys is required for receiving
   the "GALUP Certificate" by the University of Florida.

**Comment by CASSIEMOTS** [comment]
[EXERCISE 1 CASSIE.pdf](https://github.com/SERVIR-WA/GALUP/files/13372215/EXERCISE.1.CASSIE.pdf)
[EXERCISE 2.pdf](https://github.com/SERVIR-WA/GALUP/files/13372219/EXERCISE.2.pdf)

**Comment by chjch** [comment]
Well done, Kesego. You clearly grasped the material outlined in Module 1 and successfully applied it to these exercises. Thank you for your participation! If you haven't complete the post-module 1 survey, please do so [here](https://ufl.qualtrics.com/jfe/form/SV_7QjV59cEgOtfwrQ)
