### ISSUE TITLE
Victor Sensei Thela

### ISSUE THREAD

**Issue by vsthela** [SERVIR-WA/GALUP#570]
1. Please "drag & drop" exercise 1 pdf file below.

2. Please "drag & drop" exercise 2 pdf file below.

3. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.

4. If you haven't done so, please go back to Module 1 and make sure to take
   the post-training survey. Participating in surveys is required for receiving
   the "GALUP Certificate" by the University of Florida.
[Botswana Population by District in 2022.pdf](https://github.com/SERVIR-WA/GALUP/files/13378523/Botswana.Population.by.District.in.2022.pdf)
[Botswana Population Density by District in 2022.pdf](https://github.com/SERVIR-WA/GALUP/files/13378529/Botswana.Population.Density.by.District.in.2022.pdf)

**Comment by chjch** [comment]
Well done, Victor. You clearly grasped the material outlined in Module 1 and successfully applied it to these exercises. Thank you for your participation! Please make sure to finish the post-module1 survey which you can find at [here](https://servir-wa.github.io/GALUP/html/5_m1.html#exercises-and-post-training-survey).
