### ISSUE TITLE
Module 1 exercises [Doreen Mufwanzala]

### ISSUE THREAD

**Issue by Doreen50** [SERVIR-WA/GALUP#571]
1. Please "drag & drop" exercise 1 pdf file below.
[excise1.pdf](https://github.com/SERVIR-WA/GALUP/files/13391119/excise1.pdf)

2. Please "drag & drop" exercise 2 pdf file below.
[EXECISE2.pdf](https://github.com/SERVIR-WA/GALUP/files/13391123/EXECISE2.pdf)

3. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.

4. If you haven't done so, please go back to Module 1 and make sure to take
   the post-training survey. Participating in surveys is required for receiving
   the "GALUP Certificate" by the University of Florida.

**Comment by chjch** [comment]
Well done, Doreen. You clearly grasped the material outlined in Module 1 and successfully applied it to these exercises. Thank you for your participation! Please make sure to finish the post-module1 survey which you can find at [here](https://servir-wa.github.io/GALUP/html/5_m1.html#exercises-and-post-training-survey).

**Comment by Doreen50** [comment]
corrected exe.3 module2
[LAND CONDITION MODULE 3 EXR 2.pdf](https://github.com/SERVIR-WA/GALUP/files/14328723/LAND.CONDITION.MODULE.3.EXR.2.pdf)
