### ISSUE TITLE
Jess Isden

### ISSUE THREAD

**Issue by JessIsden** [SERVIR-WA/GALUP#578]
[LUCIS Module 1 Exercise 1 Map.pdf](https://github.com/SERVIR-WA/GALUP/files/13418707/LUCIS.Module.1.Exercise.1.Map.pdf)
[LUCIS Module 1 Exercise 2 Map.pdf](https://github.com/SERVIR-WA/GALUP/files/13418708/LUCIS.Module.1.Exercise.2.Map.pdf)

**Comment by chjch** [comment]
Well done, Jess. You clearly grasped the material outlined in Module 1 and successfully applied it to these exercises. Thank you for your participation! Please make sure to finish the post-module1 survey which you can find at [here](https://servir-wa.github.io/GALUP/html/5_m1.html#exercises-and-post-training-survey).
