### ISSUE TITLE
NAMATA SHANZINZA

### ISSUE THREAD

**Issue by nshanzinza** [SERVIR-WA/GALUP#583]
[Namata Shanzinza Exercise 2.pdf](https://github.com/SERVIR-WA/GALUP/files/13437302/Namata.Shanzinza.Exercise.2.pdf)

**Comment by Achidago** [comment]
Well done, Namata. You clearly grasped the material outlined in Module 1 and successfully applied it to Exercise 1.
However, you need to also complete and submit Exercise 1 to complete this module.
Thank you for your participation!
