### ISSUE TITLE
MOOKETSI SEJAMITLWA

### ISSUE THREAD

**Issue by Sejamitlwa** [SERVIR-WA/GALUP#584]
1. Please "drag & drop" exercise 1 p
[Botswana Population District in 2022.pdf](https://github.com/SERVIR-WA/GALUP/files/13437646/Botswana.Population.District.in.2022.pdf)
df file below.

2. Please "dra
[Botswana Population By Density By District in 2022 exercise 2.pdf](https://github.com/SERVIR-WA/GALUP/files/13437651/Botswana.Population.By.Density.By.District.in.2022.exercise.2.pdf)
g & drop" exercise 2 pdf file below.

3. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.

4. If you haven't done so, please go back to Module 1 and make sure to take
   the post-training survey. Participating in surveys is required for receiving
   the "GALUP Certificate" by the University of Florida.

**Comment by mogaetkpp** [comment]
Hello Mooketsi, thanks for your submission. Your map on exercise 1 looks great and well done. But, please revisit your exercise 2 and use your computed population density for your map.
