### ISSUE TITLE
Module 2 exercises [Moatlhodi Sedimo]

### ISSUE THREAD

**Issue by Sedimo9** [SERVIR-WA/GALUP#587]
1. Please "drag & drop" exercise 1 pdf file below.
[Distance to Point of Interest in Panda.pdf](https://github.com/SERVIR-WA/GALUP/files/13440696/Distance.to.Point.of.Interest.in.Panda.pdf)

2. Please "drag & drop" exercise 2 pdf file below.
[Panda IDUs in Proximity to Cattle Posts.pdf](https://github.com/SERVIR-WA/GALUP/files/13440697/Panda.IDUs.in.Proximity.to.Cattle.Posts.pdf)

3. Please "drag & drop" exercise 3 pdf file below.
[Soil Clay Content Suitability for Pandamatenga.pdf](https://github.com/SERVIR-WA/GALUP/files/13440699/Soil.Clay.Content.Suitability.for.Pandamatenga.pdf)

4. Please "drag & drop" exercise 4 pdf file below.

5. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.

6. If you haven't done so, please go back to Module 2 and make sure to take the post-training survey. Participating in surveys is required for receiving the "GALUP Certificate" by the University of Florida.
[Panda IDUs in Proximity to Cattle Posts.pdf](https://github.com/SERVIR-WA/GALUP/files/13440689/Panda.IDUs.in.Proximity.to.Cattle.Posts.pdf)

**Comment by Achidago** [comment]
Well done,Moatlhodi. You clearly grasped the material outlined in Module 2 and successfully applied it to these exercises. Thank you for your participation!
