### ISSUE TITLE
Theetso Masilomangwe

### ISSUE THREAD

**Issue by theemasi** [SERVIR-WA/GALUP#589]
1. Please "drag & drop" exercise 1 pdf file below.
[Module2_Ex_1.pdf](https://github.com/SERVIR-WA/GALUP/files/13440866/Module2_Ex_1.pdf)

2. Please "drag & drop" exercise 2 pdf file below.
[Module2_Ex_2.pdf](https://github.com/SERVIR-WA/GALUP/files/13440867/Module2_Ex_2.pdf)

3. Please "drag & drop" exercise 3 pdf file below.
[Module2_Ex_3.pdf](https://github.com/SERVIR-WA/GALUP/files/13440870/Module2_Ex_3.pdf)

4. Please "drag & drop" exercise 4 pdf file below.

5. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.

6. If you haven't done so, please go back to Module 2 and make sure to take the post-training survey. Participating in surveys is required for receiving the "GALUP Certificate" by the University of Florida.

**Comment by Achidago** [comment]
Well done, Theetso. You clearly grasped the material outlined in Module 2 and successfully applied it to these exercises. Thank you for your participation!
