### ISSUE TITLE
Module 2 exercises [DOREEN MUFWANZALA]

### ISSUE THREAD

**Issue by Doreen50** [SERVIR-WA/GALUP#590]
[EXECISE 2 CATTLE POST,MODULE 2.pdf](https://github.com/SERVIR-WA/GALUP/files/13440873/EXECISE.2.CATTLE.POST.MODULE.2.pdf)
[module 2 execise3 doreen.pdf](https://github.com/SERVIR-WA/GALUP/files/13440874/module.2.execise3.doreen.pdf)
[module 2.exercise1.pdf](https://github.com/SERVIR-WA/GALUP/files/13440876/module.2.exercise1.pdf)

**Comment by Achidago** [comment]
Well done, Doreen. You clearly grasped the material outlined in Module 2 and successfully applied it to these exercises. Thank you for your participation!
