### ISSUE TITLE
Module 2 exercises [Baagi Press Chilume]

### ISSUE THREAD

**Issue by BPChilume** [SERVIR-WA/GALUP#592]
1. Please "drag & drop" exercise 1 
[M2E1MAP.pdf](https://github.com/SERVIR-WA/GALUP/files/13441084/M2E1MAP.pdf)
pdf file below.

2. Please "drag & drop" exercise 2 pdf file below.
[EXERCISE2.pdf](https://github.com/SERVIR-WA/GALUP/files/13441088/EXERCISE2.pdf)

3. Please "drag & drop" exercise 3 pdf file below.
[M2E3.pdf](https://github.com/SERVIR-WA/GALUP/files/13441092/M2E3.pdf)

4. Please "drag & drop" exercise 4 pdf file below.

5. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.

6. If you haven't done so, please go back to Module 2 and make sure to take the post-training survey. Participating in surveys is required for receiving the "GALUP Certificate" by the University of Florida.

**Comment by Achidago** [comment]
Well done, Baagi. You clearly grasped the material outlined in Module 2 and successfully applied it to these exercises. Thank you for your participation!
