### ISSUE TITLE
Module 2 exercises [Tirelo Mpolokang}

### ISSUE THREAD

**Issue by Bopaki16** [SERVIR-WA/GALUP#593]
1. Please "drag & drop" exercise 1 
[Exersise 1.pdf](https://github.com/SERVIR-WA/GALUP/files/13441091/Exersise.1.pdf)
pdf file below.

2. Please "drag & drop" exercise 2 p
[eversise 2.pdf](https://github.com/SERVIR-WA/GALUP/files/13441094/eversise.2.pdf)
df file below.

3. Please "drag & drop" exercise 3 pdf file below.
[exercise 3.pdf](https://github.com/SERVIR-WA/GALUP/files/13441099/exercise.3.pdf)

4. Please "drag & drop" exercise 4 pdf file below.

5. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.

6. If you haven't done so, please go back to Module 2 and make sure to take the post-training survey. Participating in surveys is required for receiving the "GALUP Certificate" by the University of Florida.

**Comment by Achidago** [comment]
Well done, Tirelo. You clearly grasped the material outlined in Module 2 and successfully applied it to these exercises. Thank you for your participation!
