### ISSUE TITLE
Module 2 exercises NOBUHLE MBUSI 

### ISSUE THREAD

**Issue by nmbusi** [SERVIR-WA/GALUP#597]
1. Please "drag & drop" exercise 1 pdf file belo
[PANDAMATENGA AREA-MODULE 2 EXERCISE 1.pdf](https://github.com/SERVIR-WA/GALUP/files/13441211/PANDAMATENGA.AREA-MODULE.2.EXERCISE.1.pdf)
w.

2. Please "drag & drop" exercise 2 pdf 
[PANDAMATENGA CATTLE POST MODU 2 EXERCISE  2.pdf](https://github.com/SERVIR-WA/GALUP/files/13441214/PANDAMATENGA.CATTLE.POST.MODU.2.EXERCISE.2.pdf)
file below.

3. Please "drag & drop" exercis
[Pandamatenga reclassed Clay Contlast  MODULE 2exercise3.pdf](https://github.com/SERVIR-WA/GALUP/files/13441217/Pandamatenga.reclassed.Clay.Contlast.MODULE.2exercise3.pdf)
e 3 pdf file below.

4. Please "drag & drop" exercise 4 pdf file below.

5. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.

6. If you haven't done so, please go back to Module 2 and make sure to take the post-training survey. Participating in surveys is required for receiving the "GALUP Certificate" by the University of Florida.

**Comment by Achidago** [comment]
Well done, Nobuhle. You clearly grasped the material outlined in Module 2 and successfully applied it to these exercises. Thank you for your participation!
