### ISSUE TITLE
Dineo Puchie Ndlovu

### ISSUE THREAD

**Issue by Puchie36** [SERVIR-WA/GALUP#598]
1. Please "drag & drop" ex
[Module 2 Ex1.pdf](https://github.com/SERVIR-WA/GALUP/files/13441337/Module.2.Ex1.pdf)
ercise 1 pdf file below.

2. Please "drag & drop" exerc
[Module 2 Ex2.pdf](https://github.com/SERVIR-WA/GALUP/files/13441343/Module.2.Ex2.pdf)
ise 2 pdf file below.

3. Please "drag & drop" 
[Module 2 Ex3.pdf](https://github.com/SERVIR-WA/GALUP/files/13441351/Module.2.Ex3.pdf)
exercise 3 pdf file below.

4. Please "drag & drop" exercise 4 pdf file below.

5. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.

6. If you haven't done so, please go back to Module 2 and make sure to take the post-training survey. Participating in surveys is required for receiving the "GALUP Certificate" by the University of Florida.

**Comment by Achidago** [comment]
Well done, Dineo. You clearly grasped the material outlined in Module 2 and successfully applied it to these exercises. Thank you for your participation!
