### ISSUE TITLE
Module 2 exercises [Gadzanani Manewe]

### ISSUE THREAD

**Issue by Gmanewe1979** [SERVIR-WA/GALUP#601]
1. Please "drag & drop" exercise 1 pdf file below.

2. Please "drag & drop" exerci
[excirse 1 population distribution.pdf](https://github.com/SERVIR-WA/GALUP/files/13441599/excirse.1.population.distribution.pdf)
se 2 pdf file below.
[Uploading exercise 2 distance to point of interest.pdf…]()
[Uploading execise3 pandamatenga clay soil.pdf…]()

3. Please "drag & drop" exercise 3 pdf file below.

4. Please "drag & drop" exercise 4 pdf file below.

5. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.

6. If you haven't done so, please go back to Module 2 and make sure to take the post-training survey. Participating in surveys is required for receiving the "GALUP Certificate" by the University of Florida.

**Comment by Achidago** [comment]
Well done, Gadzanani. You clearly grasped the material outlined in Module 2 and successfully applied it to these exercises. Thank you for your participation!

**Comment by Gmanewe1979** [comment]
Thank you
