### ISSUE TITLE
 Onneetse Moleta

### ISSUE THREAD

**Issue by MMATREE** [SERVIR-WA/GALUP#602]
[module 2- exercise1.pdf](https://github.com/SERVIR-WA/GALUP/files/13442293/module.2-.exercise1.pdf)

[module 2- exerc2.pdf](https://github.com/SERVIR-WA/GALUP/files/13442296/module.2-.exerc2.pdf)w.

[modul 2- excis3.pdf](https://github.com/SERVIR-WA/GALUP/files/13442307/modul.2-.excis3.pdf)

5. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.

6. If you haven't done so, please go back to Module 2 and make sure to take the post-training survey. Participating in surveys is required for receiving the "GALUP Certificate" by the University of Florida.

**Comment by Achidago** [comment]
Well done, Onneetse. You clearly grasped the material outlined in Module 2 and successfully applied it to these exercises. Thank you for your participation!
