### ISSUE TITLE
Module 2 exercises [Kabelo Monametsi]

### ISSUE THREAD

**Issue by khyllex** [SERVIR-WA/GALUP#604]
1. Please "drag & drop" exercise 1 pdf file below.

2. Please "drag & drop" exercise 2 pdf file below.

3. Please "drag & drop" exercise 3 pdf file below.

4. Please "drag & drop" exercise 
[Distance to Point of Interest In Panda(exercise1).pdf](https://github.com/SERVIR-WA/GALUP/files/13445985/Distance.to.Point.of.Interest.In.Panda.exercise1.pdf)
4 pdf file below.
[Soil Clay Content Suitability for Pandamatenga(exercise3).pdf](https://github.com/SERVIR-WA/GALUP/files/13445990/Soil.Clay.Content.Suitability.for.Pandamatenga.exercise3.pdf)
[Panda IDUs In Proximity to Cattle Posts(exercise2).pdf](https://github.com/SERVIR-WA/GALUP/files/13445992/Panda.IDUs.In.Proximity.to.Cattle.Posts.exercise2.pdf)

5. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.

6. If you haven't done so, please go back to Module 2 and make sure to take the post-training survey. Participating in surveys is required for receiving the "GALUP Certificate" by the University of Florida.

**Comment by Achidago** [comment]
Well done, Kabelo. You clearly grasped the material outlined in Module 2 and successfully applied it to these exercises. Thank you for your participation!
