### ISSUE TITLE
Module 2 exercises [Moemedi Mbakile]

### ISSUE THREAD

**Issue by moemedim74** [SERVIR-WA/GALUP#606]
1. Please "drag & drop" exercise 1 pdf file below.
[Cattle post proximity map.pdf](https://github.com/SERVIR-WA/GALUP/files/13446541/Cattle.post.proximity.map.pdf)
2. Please "drag & drop" exercise 2 pdf file below.
[Map 2.pdf](https://github.com/SERVIR-WA/GALUP/files/13446542/Map.2.pdf)
3. Please "drag & drop" exercise 3 pdf file below.
[Module 2 Ex3.pdf](https://github.com/SERVIR-WA/GALUP/files/13446544/Module.2.Ex3.pdf)
4. Please "drag & drop" exercise 4 pdf file below.

5. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.

6. If you haven't done so, please go back to Module 2 and make sure to take the post-training survey. Participating in surveys is required for receiving the "GALUP Certificate" by the University of Florida.

**Comment by Achidago** [comment]
Well done, Moemedi. You clearly grasped the material outlined in Module 2 and successfully applied it to these exercises. Thank you for your participation!
