### ISSUE TITLE
Module 2 exercises Kedi Selume

### ISSUE THREAD

**Issue by Kedisaletse** [SERVIR-WA/GALUP#607]
[EXERCISE 3 CLAY CONTENT.pdf](https://github.com/SERVIR-WA/GALUP/files/13446595/MODULE.2.EXERCISE.3.CLAY.CONTENT.pdf)
 EXERCISE 1 KEDS.pdf](https://github.com/SERVIR-WA/GALUP/files/13446580/MODULE.2.EXERCISE.1.KEDS.pdf)
[EXERCISE 2 MODULE 2.pdf](https://github.com/SERVIR-WA/GALUP/files/13446597/EXERCISE.2.MODULE.2.pdf)

**Comment by Achidago** [comment]
Well done, Kedi. You clearly grasped the material outlined in Module 2 and successfully applied it to these exercises. Thank you for your participation!
