### ISSUE TITLE
Wesley Gwamba Module 2 exercises 

### ISSUE THREAD

**Issue by wesgwamba** [SERVIR-WA/GALUP#611]
[Soil Clay Content.pdf](https://github.com/SERVIR-WA/GALUP/files/13446770/Soil.Clay.Content.pdf)
[Panda IDUS in Proximity to Catle Posts.pdf](https://github.com/SERVIR-WA/GALUP/files/13446772/Panda.IDUS.in.Proximity.to.Catle.Posts.pdf)
[distance2.pdf](https://github.com/SERVIR-WA/GALUP/files/13446774/distance2.pdf)
1. Please "drag & drop" exercise 1 pdf file below.

2. Please "drag & drop" exercise 2 pdf file below.

3. Please "drag & drop" exercise 3 pdf file below.

4. Please "drag & drop" exercise 4 pdf file below.

5. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.

6. If you haven't done so, please go back to Module 2 and make sure to take the post-training survey. Participating in surveys is required for receiving the "GALUP Certificate" by the University of Florida.

**Comment by Achidago** [comment]
Well done, Wesley. You clearly grasped the material outlined in Module 2 and successfully applied it to these exercises. Thank you for your participation!
