### ISSUE TITLE
Olefile Maikaelelo-Module 2 exercises 

### ISSUE THREAD

**Issue by omaikaelelo** [SERVIR-WA/GALUP#612]
1. Please "drag & drop" exercise 1 pdf file below.
[Distance to Point_Panda.pdf](https://github.com/SERVIR-WA/GALUP/files/13446789/Distance.to.Point_Panda.pdf)

2. Please "drag & drop" exercise 2 pdf file below.
[Selection by Location_Panda Cattle Post.pdf](https://github.com/SERVIR-WA/GALUP/files/13446791/Selection.by.Location_Panda.Cattle.Post.pdf)

3. Please "drag & drop" exercise 3 pdf file below.
[Soil Clay Suitability for Pandamatenga.pdf](https://github.com/SERVIR-WA/GALUP/files/13446794/Soil.Clay.Suitability.for.Pandamatenga.pdf)

5. Please "drag & drop" exercise 4 pdf file below.

6. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.

7. If you haven't done so, please go back to Module 2 and make sure to take the post-training survey. Participating in surveys is required for receiving the "GALUP Certificate" by the University of Florida.

**Comment by Achidago** [comment]
Well done, Olefile. You clearly grasped the material outlined in Module 2 and successfully applied it to these exercises. Thank you for your participation!
