### ISSUE TITLE
KEDI SELUME MODULE 2 EXERCISE

### ISSUE THREAD

**Issue by Kedisaletse** [SERVIR-WA/GALUP#616]
EXERCISE 2
[CATTLEPOSTS EXERCISE 2 MODULE 2.pdf](https://github.com/SERVIR-WA/GALUP/files/13448408/CATTLEPOSTS.EXERCISE.2.MODULE.2.pdf)

**Comment by Achidago** [comment]
Seen. Thank you for your participation!
