### ISSUE TITLE
Module 1 exercises [replace with your name]

### ISSUE THREAD

**Issue by Gmanewe1979** [SERVIR-WA/GALUP#619]
1. Please "drag & drop" exercise 1 pdf file below.

2. Please "drag & drop" exercise 2 
[module1 excirse 1.pdf](https://github.com/SERVIR-WA/GALUP/files/13455741/module1.excirse.1.pdf)
pdf file below.

3. Please UPDATE THE TITL
[module 1 excirse 1,botswana population.pdf](https://github.com/SERVIR-WA/GALUP/files/13455738/module.1.excirse.1.botswana.population.pdf)
E of this "Issue" in the title bar above with your name.

4. If you haven't done so, please go back to Module 1 and make sure to take
   the post-training survey. Participating in surveys is required for receiving
   the "GALUP Certificate" by the University of Florida.

**Comment by Achidago** [comment]
Well done, Gadzanani. You clearly grasped the material outlined in Module 1 and successfully applied it to these exercises. Thank you for your participation!

**Comment by Gmanewe1979** [comment]
Thank you
