### ISSUE TITLE
Module 3 exercise (Tirelo Mpolokang)

### ISSUE THREAD

**Issue by Bopaki16** [SERVIR-WA/GALUP#620]
1. Please "drag & drop" exercis
[Land Scape Condition.pdf](https://github.com/SERVIR-WA/GALUP/files/13456723/Land.Scape.Condition.pdf)
e 1 pdf file below.

2. Please "drag & drop" exercise 2 pdf file below.

3. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.

4. If you haven't done so, please go back to Module 3 and make sure to take
   the post-training survey. Participating in surveys is required for receiving
   the "GALUP Certificate" by the University of Florida.

**Comment by Achidago** [comment]
Well done,Tirelo. You clearly grasped the material outlined in Module 1 and successfully applied it to these exercises. Thank you for your participation!
