### ISSUE TITLE
Module 3 exercises  Nobuhle Mbusi]

### ISSUE THREAD

**Issue by nmbusi** [SERVIR-WA/GALUP#631]
1. Please "drag & drop" exercise 1 pdf file below.
[LAND SCAPE SUITABILITY-MODULE 3 EXERCISE 1.pdf](https://github.com/SERVIR-WA/GALUP/files/13458368/LAND.SCAPE.SUITABILITY-MODULE.3.EXERCISE.1.pdf)

2. Please "drag & drop" exercise 2 pdf file below.

3. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.

4. If you haven't done so, please go back to Module 3 and make sure to take
   the post-training survey. Participating in surveys is required for receiving
   the "GALUP Certificate" by the University of Florida.

**Comment by Achidago** [comment]
Well done, Nobuhle. You clearly grasped the material outlined in Module 1 and successfully applied it to this exercise. Thank you for your participation!
