### ISSUE TITLE
Module 3 exercises [Onneetse Moleta]

### ISSUE THREAD

**Issue by MMATREE** [SERVIR-WA/GALUP#636]
[mod 3 EX 1 land condition in Panda.pdf](https://github.com/SERVIR-WA/GALUP/files/13458977/mod.3.EX.1.land.condition.in.Panda.pdf)

**Comment by chjch** [comment]
Well done, Onneetse. You clearly grasped the material outlined in Module 3 and successfully applied it to these exercises. Thank you for your participation!
