### ISSUE TITLE
Module 3 exercises [Gadzanani Manewe]

### ISSUE THREAD

**Issue by Gmanewe1979** [SERVIR-WA/GALUP#638]
1. Please "drag & drop" exercise 1 pdf file below.

2. Please "drag & drop" exercise 2 pdf file below.

3. Please UPDATE T
[module 3 execise1 land scape.pdf](https://github.com/SERVIR-WA/GALUP/files/13459673/module.3.execise1.land.scape.pdf)
HE TITLE of this "Issue" in the title bar above with your name.

4. If you haven't done so, please go back to Module 3 and make sure to take
   the post-training survey. Participating in surveys is required for receiving
   the "GALUP Certificate" by the University of Florida.

**Comment by chjch** [comment]
Well done, Gadzanani. You clearly grasped the material outlined in Module 3 and successfully applied it to these exercises. Thank you for your participation!

**Comment by Gmanewe1979** [comment]
Than you
