### ISSUE TITLE
Module 3 exercises [Ikanyeng Pearl Sediakgotla]

### ISSUE THREAD

**Issue by isediakgotla** [SERVIR-WA/GALUP#640]
1. Please "dra
[Land Condition in Pandamatenga, Botswana.pdf](https://github.com/SERVIR-WA/GALUP/files/13460279/Land.Condition.in.Pandamatenga.Botswana.pdf)
g & drop" exercise 1 pdf file below.

2. Please "drag & drop" exercise 2 pdf file below.

3. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.

4. If you haven't done so, please go back to Module 3 and make sure to take
   the post-training survey. Participating in surveys is required for receiving
   the "GALUP Certificate" by the University of Florida.

**Comment by chjch** [comment]
Well done, Ikanyeng. You clearly grasped the material outlined in Module 3 and successfully applied it to these exercises. Thank you for your participation!
