### ISSUE TITLE
Module 3 exercises [Baagi Press Chilume]

### ISSUE THREAD

**Issue by BPChilume** [SERVIR-WA/GALUP#642]
1. Please "drag & drop
[Land Condition Map.pdf](https://github.com/SERVIR-WA/GALUP/files/13460644/Land.Condition.Map.pdf)
" exercise 1 pdf file below.

2. Please "drag & drop" exercise 2 pdf file below.

3. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.

4. If you haven't done so, please go back to Module 3 and make sure to take
   the post-training survey. Participating in surveys is required for receiving
   the "GALUP Certificate" by the University of Florida.

**Comment by chjch** [comment]
Well done, Baagi. You clearly grasped the material outlined in Module 3 and successfully applied it to these exercises. Thank you for your participation!
