### ISSUE TITLE
Module 4 exercises [Onneetse Moleta]

### ISSUE THREAD

**Issue by MMATREE** [SERVIR-WA/GALUP#643]
[module 4.xlsx](https://github.com/SERVIR-WA/GALUP/files/13461531/module.4.xlsx)

**Comment by chjch** [comment]
Well done, Onneetse. You clearly grasped the material outlined in Module 4 and successfully applied it to these exercises. Thank you for your participation! Please make sure to complete the post-training survey [here](https://ufl.qualtrics.com/jfe/form/SV_a9QP5kcZfMckQSi).
