### ISSUE TITLE
Namata Shanzinza,Module 2 exercises 

### ISSUE THREAD

**Issue by nshanzinza** [SERVIR-WA/GALUP#644]
[Clay conti-MODULE 2 EXERCISE 3.pdf](https://github.com/SERVIR-WA/GALUP/files/13464597/Clay.conti-MODULE.2.EXERCISE.3.pdf)
[PANDA IDUS -CATTLE POST MODULE2 EXERCISE 2.pdf](https://github.com/SERVIR-WA/GALUP/files/13464598/PANDA.IDUS.-CATTLE.POST.MODULE2.EXERCISE.2.pdf)
[point distance map.pdf](https://github.com/SERVIR-WA/GALUP/files/13464599/point.distance.map.pdf)
[PANDA IDUS -CATTLE POST MODULE2 EXERCISE 2.pdf](https://github.com/SERVIR-WA/GALUP/files/13464600/PANDA.IDUS.-CATTLE.POST.MODULE2.EXERCISE.2.pdf)
[Uploading point distance map.pdf…]()

**Comment by chjch** [comment]
Well done, Namata. You clearly grasped the material outlined in Module 2 and successfully applied it to these exercises. Thank you for your participation!
