### ISSUE TITLE
Module 2 exercises [Nada N. Tandoh]

### ISSUE THREAD

**Issue by Nadat1968** [SERVIR-WA/GALUP#66]
1. Please "drag & drop" exercise 1 pdf file below.
[ROAD DENSITY FOR THLD_Assignment 1.pdf](https://github.com/SERVIR-WA/GALUP/files/6663283/ROAD.DENSITY.FOR.THLD_Assignment.1.pdf)

2. Please "drag & drop" exercise 2 pdf file below.
[Health Facilities_Assignment 2.pdf](https://github.com/SERVIR-WA/GALUP/files/6663285/Health.Facilities_Assignment.2.pdf)

3. Please "drag & drop" exercise 3 pdf file below.
[Educational Facilities_Assignment 3.pdf](https://github.com/SERVIR-WA/GALUP/files/6663286/Educational.Facilities_Assignment.3.pdf)

4. Please "drag & drop" exercise 4 pdf file below.
[Soil Suitability_Assignment 4.pdf](https://github.com/SERVIR-WA/GALUP/files/6663287/Soil.Suitability_Assignment.4.pdf)

5. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.

6. If you haven't done so, please go back to Module 2 and make sure to take
   the post-training survey. Participating in surveys is required for receiving
   the "GALUP Certificate" by the University of Florida.

**Comment by muribasterra** [comment]
Well done, Nada. You clearly grasped the material outlined in Module 2 and successfully applied it to these exercises. I liked your addition of health facility symbols for Exercise 2.
Thank you for your participation!
