### ISSUE TITLE
Module 4 exercises [Tirelo Mpolokang]

### ISSUE THREAD

**Issue by Bopaki16** [SERVIR-WA/GALUP#666]
1. Please "drag & drop" exercise 1 e
[Module 4 exercise 1 & 2.xlsx](https://github.com/SERVIR-WA/GALUP/files/13515884/Module.4.exercise.1.2.xlsx)
xcel file below.

2. Please "drag & drop" exercise 2 excel file below.

3. Please "drag & drop" exercise 3 pdf file below.

4. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.

5. If you haven't done so, please go back to Module 4 and make sure to take
   the post-training survey. Participating in surveys is required for receiving
   the "GALUP Certificate" by the University of Florida.

**Comment by chjch** [comment]
Can you please let me know your name and which institution you are from?

**Comment by Bopaki16** [comment]
Tirelo Mpolokang from Chobe Land Board

**Comment by chjch** [comment]
Well done, Tirelo. You clearly grasped the material outlined in Module 4 and successfully applied it to these exercises. Thank you for your participation! Please make sure to complete the post-training survey [here](https://ufl.qualtrics.com/jfe/form/SV_a9QP5kcZfMckQSi).
