### ISSUE TITLE
Module 4 exercises [Theetso Masilomangwe]

### ISSUE THREAD

**Issue by theemasi** [SERVIR-WA/GALUP#678]
[MODULE4_EX1.xlsx](https://github.com/SERVIR-WA/GALUP/files/13527788/MODULE4_EX1.xlsx)
[MODULE4_EX2.xlsx](https://github.com/SERVIR-WA/GALUP/files/13527789/MODULE4_EX2.xlsx)

**Comment by Achidago** [comment]
Well done, Theetso. You clearly grasped the material outlined in Module 4 and successfully applied it to these exercises. Thank you for your participation! Please make sure to complete the post-training survey [here](https://ufl.qualtrics.com/jfe/form/SV_a9QP5kcZfMckQSi).
