### ISSUE TITLE
Module 1 exercises Kabelo A .Monametsi

### ISSUE THREAD

**Issue by khyllex** [SERVIR-WA/GALUP#686]
1. Please "drag & drop" exercise 1 pdf file below.

2. Please "drag & drop" exercise 2 pdf file below.

3. Please UPDATE THE TITLE of this "Issue" in t
[exercise 1.pdf](https://github.com/SERVIR-WA/GALUP/files/13536796/exercise.1.pdf)
[exercise 2.pdf](https://github.com/SERVIR-WA/GALUP/files/13536797/exercise.2.pdf)

he title bar above with your name.

4. If you haven't done so, please go back to Module 1 and make sure to take
   the post-training survey. Participating in surveys is required for receiving
   the "GALUP Certificate" by the University of Florida.

**Comment by Achidago** [comment]
Well done, Kabelo. You clearly grasped the material outlined in Module 1 and successfully applied it to these exercises. Thank you for your participation!
