### ISSUE TITLE
Module 3 exercises [Kabelo A. Monametsi ]

### ISSUE THREAD

**Issue by khyllex** [SERVIR-WA/GALUP#687]
1. Please "drag & drop" exercise 1 pdf file below.

2. Please "drag & drop" exercise 2 pdf file below.
[MODULE3.pdf](https://github.com/SERVIR-WA/GALUP/files/13536818/MODULE3.pdf)

3. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.

4. If you haven't done so, please go back to Module 3 and make sure to take
   the post-training survey. Participating in surveys is required for receiving
   the "GALUP Certificate" by the University of Florida.

**Comment by Achidago** [comment]
Well done, Kabelo. You clearly grasped the material outlined in Module 3 and successfully applied it to the exercise. Thank you for your participation!
