### ISSUE TITLE
Module 4 exercises [Kabelo A.  Monametsi]

### ISSUE THREAD

**Issue by khyllex** [SERVIR-WA/GALUP#688]
1. Please "drag & drop" exercise 1 excel file below.

2. Please "drag & drop" exercise 2 excel file belo
[AHP.xlsx](https://github.com/SERVIR-WA/GALUP/files/13536822/AHP.xlsx)
w.

3. Please "drag & drop" exercise 3 pdf file below.

4. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.

5. If you haven't done so, please go back to Module 4 and make sure to take
   the post-training survey. Participating in surveys is required for receiving
   the "GALUP Certificate" by the University of Florida.

**Comment by Achidago** [comment]
Hi Kabelo, your exercise 2 has a slight issue as there is no value for the priority vector for row crops. Please check and re-upload it. You can do that in a new comment.

**Comment by Achidago** [comment]
Also, kindly submit Module 4, Exercise 1 if you haven't already done so.

**Comment by khyllex** [comment]
[AHP_Resubmission.xlsx](https://github.com/SERVIR-WA/GALUP/files/13615175/AHP_Resubmission.xlsx)-Kabelo A.Monametsi


kindly find the corrected AHP

**Comment by Achidago** [comment]
Well done, Kabelo. You clearly grasped the material outlined in Module 4 and successfully applied it to these exercises. Thank you for your participation! Please make sure to complete the post-training survey [here](https://ufl.qualtrics.com/jfe/form/SV_a9QP5kcZfMckQSi).

**Comment by Achidago** [comment]
Hi Kabelo, please submit Module 4 Exercise 1 as well. Thank you!

**Comment by khyllex** [comment]
hi Silas ..I have re-sent the module 4 exercise 2 corrections last week for
your review.Module 4 exercise 1 is on another sheet 1 named exercise 1 on
the same wookbook.

**Comment by Achidago** [comment]
Well done, Kabelo. You clearly grasped the material outlined in Module 4 and successfully applied it to these exercises. Thank you for your participation! Please make sure to complete the post-training survey [here](https://ufl.qualtrics.com/jfe/form/SV_a9QP5kcZfMckQSi).
