### ISSUE TITLE
Module 3 exercise 1 - Namata Shanzinza 

### ISSUE THREAD

**Issue by nshanzinza** [SERVIR-WA/GALUP#691]
[Land Condition in Pandamatenga Botswana.pdf](https://github.com/SERVIR-WA/GALUP/files/13546912/Land.Condition.in.Pandamatenga.Botswana.pdf)

**Comment by chjch** [comment]
Well done, Namata. You clearly grasped the material outlined in Module 3 and successfully applied it to these exercises. Thank you for your participation!
