### ISSUE TITLE
Module 4 exercises [GOABAONE NTLOEDIBE] corrected

### ISSUE THREAD

**Issue by Rauwegis** [SERVIR-WA/GALUP#695]
1. Please "drag & drop" exercise 1 excel file below.

2. Please "drag & drop" exercise 2 excel file below.
[Uploading MODULE 4.EXE2-NTLOEDIBE.xlsx…]()

3. Please "drag & drop" exercise 3 pdf file below.

4. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.

5. If you haven't done so, please go back to Module 4 and make sure to take
   the post-training survey. Participating in surveys is required for receiving
   the "GALUP Certificate" by the University of Florida.

**Comment by chjch** [comment]
see #694 . Wrong name in title. GOABAONE NTLOEDIBE has submitted, see #655
