### ISSUE TITLE
Module 4 exercise 2

### ISSUE THREAD

**Issue by nshanzinza** [SERVIR-WA/GALUP#699]
[MODULE 4 ex2.xlsx](https://github.com/SERVIR-WA/GALUP/files/13561032/MODULE.4.ex2.xlsx)

**Comment by chjch** [comment]
Well done, Namata. You clearly grasped the material outlined in Module 4 and successfully applied it to these exercises. Thank you for your participation! Please make sure to complete the post-training survey [here](https://ufl.qualtrics.com/jfe/form/SV_a9QP5kcZfMckQSi).
