### ISSUE TITLE
Module 4 exercises Senzeni Mafara

### ISSUE THREAD

**Issue by SenzeniMafara** [SERVIR-WA/GALUP#700]
[Module four exercise 1.xlsx](https://github.com/SERVIR-WA/GALUP/files/13561074/Module.four.exercise.1.xlsx)
[Module four exercise 2.xlsx](https://github.com/SERVIR-WA/GALUP/files/13561075/Module.four.exercise.2.xlsx)

**Comment by chjch** [comment]
same as #701
