### ISSUE TITLE
Module 4 exercises [replace with your name]

### ISSUE THREAD

**Issue by SenzeniMafara** [SERVIR-WA/GALUP#701]
[Module four exercise 1.xlsx](https://github.com/SERVIR-WA/GALUP/files/13561074/Module.four.exercise.1.xlsx)
[Module four exercise 2.xlsx](https://github.com/SERVIR-WA/GALUP/files/13561075/Module.four.exercise.2.xlsx)

**Comment by chjch** [comment]
Well done, Senzeni. You clearly grasped the material outlined in Module 4 and successfully applied it to these exercises. Thank you for your participation! Please make sure to complete the post-training survey [here](https://ufl.qualtrics.com/jfe/form/SV_a9QP5kcZfMckQSi).
