### ISSUE TITLE
Module 2 exercises [replace with your name]

### ISSUE THREAD

**Issue by glsewetse** [SERVIR-WA/GALUP#704]
1. Please "drag & drop" exerci
[Exersise 2 Module 1.pdf](https://github.com/SERVIR-WA/GALUP/files/13614408/Exersise.2.Module.1.pdf)
se 1 pdf file below.

2. Please "drag & drop" exercis
[Module 2 Eversise 2.pdf](https://github.com/SERVIR-WA/GALUP/files/13614410/Module.2.Eversise.2.pdf)
e 2 pdf file below.

3. Please "drag & drop"
[Uploading Module 2 Exercise 3.pdf…]()
 exercise 3 pdf file below.

4. Please "drag & drop" exercise 4 pdf file below.

5. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.

6. If you haven't done so, please go back to Module 2 and make sure to take the post-training survey. Participating in surveys is required for receiving the "GALUP Certificate" by the University of Florida.

**Comment by Achidago** [comment]
Well done, Goemeoni. Thanks for submitting exercise 1 and 2. It is perfect! To complete this module, please submit your exercise 3 by editing your submission or attaching it in a comment below. Thanks!

**Comment by Achidago** [comment]
Seen in the other submission.
