### ISSUE TITLE
Module 2 exercises [Goemeone L. Sewetse

### ISSUE THREAD

**Issue by glsewetse** [SERVIR-WA/GALUP#705]
1
[Module 2 Exercise 1.pdf](https://github.com/SERVIR-WA/GALUP/files/13614485/Module.2.Exercise.1.pdf)
. Please "drag & drop" exercise 1 pdf file below.

2. Please
[Module 2 Eversise 2.pdf](https://github.com/SERVIR-WA/GALUP/files/13614496/Module.2.Eversise.2.pdf)
 "drag & drop

3. Please "drag & dro
[Module 2 Exercise 3.pdf](https://github.com/SERVIR-WA/GALUP/files/13614501/Module.2.Exercise.3.pdf)
p" exercise 3 pdf file below.

4. Please "drag & drop" exercise 4 pdf file below.

5. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.

6. If you haven't done so, please go back to Module 2 and make sure to take the post-training survey. Participating in surveys is required for receiving the "GALUP Certificate" by the University of Florida.

**Comment by Achidago** [comment]
Well done, Goemeone. You clearly grasped the material outlined in Module 2 and successfully applied it to these exercises. Thank you for your participation!
