### ISSUE TITLE
Module 1 exercises [Goemeone L. Sewetse]

### ISSUE THREAD

**Issue by glsewetse** [SERVIR-WA/GALUP#706]
1. Please "drag & drop" exercise 1
[Exercise1 Module1.pdf](https://github.com/SERVIR-WA/GALUP/files/13614306/Exercise1.Module1.pdf)
 pdf file below.

2. Please "drag & drop" exerci
[Exersise 2 Module 1.pdf](https://github.com/SERVIR-WA/GALUP/files/13614309/Exersise.2.Module.1.pdf)
se 2 pdf file below.

3. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.

4. If you haven't done so, please go back to Module 1 and make sure to take
   the post-training survey. Participating in surveys is required for receiving
   the "GALUP Certificate" by the University of Florida.

**Comment by Achidago** [comment]
Well done,Goemeone. You clearly grasped the material outlined in Module 1 and successfully applied it to these exercises. Thank you for your participation!
