### ISSUE TITLE
Module 3 Exercise 1 KEDI SELUME 

### ISSUE THREAD

**Issue by Kedisaletse** [SERVIR-WA/GALUP#712]
[LAND CONDITION MODULE 3 EXERCISE 1.pdf](https://github.com/SERVIR-WA/GALUP/files/13648879/LAND.CONDITION.MODULE.3.EXERCISE.1.pdf)

**Comment by Achidago** [comment]
Well done, Kedi. You clearly grasped the material outlined in Module 3 and successfully applied it to this exercise. Thank you for your participation!
