### ISSUE TITLE
Module 1 exercises [replace with your name]

### ISSUE THREAD

**Issue by Sejamitlwa** [SERVIR-WA/GALUP#714]
1. Please "drag & drop" exercise 1 pdf file below.

2. Please "drag & dro
[Botswana Populatrion By Density in 2022 new.pdf](https://github.com/SERVIR-WA/GALUP/files/13658940/Botswana.Populatrion.By.Density.in.2022.new.pdf)
p" exercise 2 pdf file below.

3. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.

4. If you haven't done so, please go back to Module 1 and make sure to take
   the post-training survey. Participating in surveys is required for receiving
   the "GALUP Certificate" by the University of Florida.

**Comment by mogaetkpp** [comment]
Thanks for your submission Mooketsi. Well done.
