### ISSUE TITLE
Module 1 exercises [Bakwena Keabetswe]

### ISSUE THREAD

**Issue by Bakwena** [SERVIR-WA/GALUP#715]
1. Please "drag & drop" exercise 1 pdf file below.
[Module 1 - Exercise 1.pdf](https://github.com/SERVIR-WA/GALUP/files/13659672/Module.1.-.Exercise.1.pdf)
2. Please "drag & drop" exercise 2 pdf file below.
[Module 1 - exercise2.pdf](https://github.com/SERVIR-WA/GALUP/files/13659673/Module.1.-.exercise2.pdf)
3. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.

4. If you haven't done so, please go back to Module 1 and make sure to take
   the post-training survey. Participating in surveys is required for receiving
   the "GALUP Certificate" by the University of Florida.

**Comment by mogaetkpp** [comment]
Thanks Bakwena for submitting your exercises for module 1. You have now grasped the basics of QGIS, please continue with other modules to learn the use of QGIS tools on suitability analysis. Thanks.
