### ISSUE TITLE
Module 3 exercises 1 resubmission - Senzeni Mafara

### ISSUE THREAD

**Issue by SenzeniMafara** [SERVIR-WA/GALUP#716]
[PANDAMATENGA LAND CONDITION - resubmission.pdf](https://github.com/SERVIR-WA/GALUP/files/13661004/PANDAMATENGA.LAND.CONDITION.-.resubmission.pdf)

**Comment by mogaetkpp** [comment]
Thanks for your submission Mrs Mafara. Let me bring this to @chjch or Silas attention so they see why the starting value is less than 1.

**Comment by Achidago** [comment]
Well done, Senzeni. You clearly grasped the material outlined in Module 3 and successfully applied it to this exercise. Thank you for your participation!
