### ISSUE TITLE
Wesley Gwamba module 1]

### ISSUE THREAD

**Issue by wesgwamba** [SERVIR-WA/GALUP#718]
[BOTSWANA POPULATION BY DISTRICT IN 2023.pdf](https://github.com/SERVIR-WA/GALUP/files/13669876/BOTSWANA.POPULATION.BY.DISTRICT.IN.2023.pdf)
1. Please "drag & drop" exercise 1 pdf file below.

2. Please "drag & drop" exercise 2 pdf file below.
[Botswana Population Density by District in 2022.pdf](https://github.com/SERVIR-WA/GALUP/files/13669878/Botswana.Population.Density.by.District.in.2022.pdf)

3. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.

4. If you haven't done so, please go back to Module 1 and make sure to take
   the post-training survey. Participating in surveys is required for receiving
   the "GALUP Certificate" by the University of Florida.

**Comment by Achidago** [comment]
Well done, Wesley. You clearly grasped the material outlined in Module 1 and successfully applied it to this exercise. Thank you for your participation!
