### ISSUE TITLE
Module 2 exercises [Bakwena Keabetswe]

### ISSUE THREAD

**Issue by Bakwena** [SERVIR-WA/GALUP#721]
1. Please "drag & drop" exercise 1 pdf file below.
[exercise 1.pdf](https://github.com/SERVIR-WA/GALUP/files/13674590/exercise.1.pdf)

2. Please "drag & drop" exercise 2 pdf file below.
[Exercise 2 - M2.pdf](https://github.com/SERVIR-WA/GALUP/files/13674594/Exercise.2.-.M2.pdf)

3. Please "drag & drop" exercise 3 pdf file below.
[exercise 3.pdf](https://github.com/SERVIR-WA/GALUP/files/13674598/exercise.3.pdf)

4. Please "drag & drop" exercise 4 pdf file below.

5. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.

6. If you haven't done so, please go back to Module 2 and make sure to take the post-training survey. Participating in surveys is required for receiving the "GALUP Certificate" by the University of Florida.

**Comment by mogaetkpp** [comment]
Thanks for your submission Bakwena. You have done well and showed you grasped the use of the tools. Keep pushing!
