### ISSUE TITLE
Module 4 exercises FINAL RESUBMISSION[K.MOTSWASELE]

### ISSUE THREAD

**Issue by CASSIEMOTS** [SERVIR-WA/GALUP#726]
1. Please "drag & drop" exercise 1 
[EXERCISE 1 & 2 CORRECTION.xlsx](https://github.com/SERVIR-WA/GALUP/files/14073475/EXERCISE.1.2.CORRECTION.xlsx)
excel file below.

2. Please "drag & drop" exercise 2 excel file below.

3. Please "drag & drop" exercise 3 pdf file below.

4. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.

5. If you haven't done so, please go back to Module 4 and make sure to take
   the post-training survey. Participating in surveys is required for receiving
   the "GALUP Certificate" by the University of Florida.

**Comment by mogaetkpp** [comment]
Thank you Kesego for making corrections to your module 4 exercises. They are now correct and seems now you have grasped the module content. You have now completed the training, congratulations.
