### ISSUE TITLE
Module 4 exercises [Moemedi Mbakile]

### ISSUE THREAD

**Issue by moemedim74** [SERVIR-WA/GALUP#727]
1. Please "drag & drop" exercise 1 excel file below.

2. Please "drag & dr
[EXERCISE 2 MODULE 4 RESUBMISSION.xlsx](https://github.com/SERVIR-WA/GALUP/files/14076825/EXERCISE.2.MODULE.4.RESUBMISSION.xlsx)
op" exercise 2 excel file below.

3. Please "drag & drop" exercise 3 pdf file below.

4. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.

5. If you haven't done so, please go back to Module 4 and make sure to take
   the post-training survey. Participating in surveys is required for receiving
   the "GALUP Certificate" by the University of Florida.

**Comment by mogaetkpp** [comment]
Thank you Mr Mbakile for submitting your module 4 exercises. Your submissions are correct. Congratulations for completing the training.  Thank you.

**Comment by moemedim74** [comment]
Good morning Mr Mogae.
Sorry I was out of town for the past 2 weeks. I only came back last week on Thursday.  It is my ardent hope that everything is now in order.
Thanks 

Sent from Yahoo Mail on Android 
 
  On Mon, 29 Jan 2024 at 10:30, Mogae ***@***.***> wrote:   


Thank you Mr Mbakile for submitting your module 4 exercises. Your submissions are correct. Congratulations for completing the training. Thank you.

**Comment by moemedim74** [comment]
Via 


Sent from Yahoo Mail on Android 
 
  On Mon, 29 Jan 2024 at 11:05, mbakile ***@***.***> wrote:   Good morning Mr Mogae.
Sorry I was out of town for the past 2 weeks. I only came back last week on Thursday.  It is my ardent hope that everything is now in order.
Thanks 

Sent from Yahoo Mail on Android 
 
  On Mon, 29 Jan 2024 at 10:30, Mogae ***@***.***> wrote:   


Thank you Mr Mbakile for submitting your module 4 exercises. Your submissions are correct. Congratulations for completing the training. Thank you.
