### ISSUE TITLE
Module 2 exercises Judith Nommo Dery]

### ISSUE THREAD

**Issue by Jnommo** [SERVIR-WA/GALUP#74]
[Exercise 3 Judith.pdf](https://github.com/SERVIR-WA/GALUP/files/6687143/Exercise.3.Judith.pdf)
[Exercise 4 Judith.pdf](https://github.com/SERVIR-WA/GALUP/files/6687144/Exercise.4.Judith.pdf)

1. Please "drag & drop" exercise 1 pdf file below.

2. Please "drag & drop" exercise 2 pdf file below.

3. Please "drag & drop" exercise 3 pdf file below.

4. Please "drag & drop" exercise 4 pdf file below.

5. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.

6. If you haven't done so, please go back to Module 2 and make sure to take
   the post-training survey. Participating in surveys is required for receiving
   the "GALUP Certificate" by the University of Florida.

**Comment by muribasterra** [comment]
Hi Judith, I'm still missing exercises 1 and 2 here.

**Comment by Jnommo** [comment]
I sent assignments 1 and 2 a while back and was given feedback on them. I am adding them all here
[Galup 1 Judith.pdf](https://github.com/SERVIR-WA/GALUP/files/6765259/Galup.1.Judith.pdf)
[Galup 2 Judith.pdf](https://github.com/SERVIR-WA/GALUP/files/6765260/Galup.2.Judith.pdf)
[Exercise 4 Judith.pdf](https://github.com/SERVIR-WA/GALUP/files/6765264/Exercise.4.Judith.pdf)
[Exercise 3 Judith.pdf](https://github.com/SERVIR-WA/GALUP/files/6765265/Exercise.3.Judith.pdf)
 though. Thank you.

**Comment by muribasterra** [comment]
My mistake! I’ll close out the issue now.
