### ISSUE TITLE
Prosper Kwame Detornu

### ISSUE THREAD

**Issue by Prosper-Detornu** [SERVIR-WA/GALUP#75]
[Prosper Detornu_Distance to Health Facility in THLD District.pdf](https://github.com/SERVIR-WA/GALUP/files/6710391/Prosper.Detornu_Distance.to.Health.Facility.in.THLD.District.pdf)
[Prosper Detornu_Soil pH Suitability Index by IDUs in THLD District.pdf](https://github.com/SERVIR-WA/GALUP/files/6710393/Prosper.Detornu_Soil.pH.Suitability.Index.by.IDUs.in.THLD.District.pdf)
[Prosper Detornu_THLD IDUs in Proximity to the Education Facilities.pdf](https://github.com/SERVIR-WA/GALUP/files/6710395/Prosper.Detornu_THLD.IDUs.in.Proximity.to.the.Education.Facilities.pdf)
[Prosper Detornu_THLD Road Network Density by IDU.pdf](https://github.com/SERVIR-WA/GALUP/files/6710396/Prosper.Detornu_THLD.Road.Network.Density.by.IDU.pdf)
1. Please "drag & drop" exercise 1 pdf file below.

2. Please "drag & drop" exercise 2 pdf file below.

3. Please "drag & drop" exercise 3 pdf file below.

4. Please "drag & drop" exercise 4 pdf file below.

5. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.

6. If you haven't done so, please go back to Module 2 and make sure to take
   the post-training survey. Participating in surveys is required for receiving
   the "GALUP Certificate" by the University of Florida.

**Comment by muribasterra** [comment]
Well done, Prosper. You clearly grasped the material outlined in Module 2 and successfully applied it to these exercises. Thank you for your participation!
