### ISSUE TITLE
Module 1 exercises [Julie Peeling]

### ISSUE THREAD

**Issue by JuliePeeling** [SERVIR-WA/GALUP#8]
1. Please drag & drop exercise 1 pdf file below.
[GALUPmod1Population.pdf](https://github.com/SERVIR-WA/GALUP/files/6554952/GALUPmod1Population.pdf)
2. Please drag & drop exercise 2 pdf file below.
[GALUPmod1PopDen.pdf](https://github.com/SERVIR-WA/GALUP/files/6554957/GALUPmod1PopDen.pdf)
3. Make sure to update the title with your name.

4. If you have any comments about this exercise, please leave it below.
These exercises were a very useful introduction to QGIS, and I thought all of the extra links to resources were extremely helpful. The only issue that I could find was in the introduction section to Module 1, under 3.5 there is a link that says "See the example map in PDF file here." However, when I click the link, it takes me to an error page on GitHub. I thought I would let you know of this issue in case it had not been previously brought up. Thank you!

**Comment by chjch** [comment]
Good job, Julie!
