### ISSUE TITLE
Module 2 exercises [Francisca Ameley Armah_CERSGIS]

### ISSUE THREAD

**Issue by ameley1** [SERVIR-WA/GALUP#82]
1. Please "drag & drop" exercise 1 pdf file below.
[THLD Road Network Density by IDU.pdf](https://github.com/SERVIR-WA/GALUP/files/6764437/THLD.Road.Network.Density.by.IDU.pdf)

2. Please "drag & drop" exercise 2 pdf file below.
[Distance to health Facility in THLD Districts.pdf](https://github.com/SERVIR-WA/GALUP/files/6764431/Distance.to.health.Facility.in.THLD.Districts.pdf)

3. Please "drag & drop" exercise 3 pdf file below.
[THLD IDUs in Proximity to the Education Facilities.pdf](https://github.com/SERVIR-WA/GALUP/files/6764426/THLD.IDUs.in.Proximity.to.the.Education.Facilities.pdf)

4. Please "drag & drop" exercise 4 pdf file below.
[Soil PH Suitability index by IDUs in THLD District.pdf](https://github.com/SERVIR-WA/GALUP/files/6764415/Soil.PH.Suitability.index.by.IDUs.in.THLD.District.pdf)

5. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.

6. If you haven't done so, please go back to Module 2 and make sure to take
   the post-training survey. Participating in surveys is required for receiving
   the "GALUP Certificate" by the University of Florida.

**Comment by muribasterra** [comment]
Well done,, Francisca. You clearly grasped the material outlined in Module 2 and successfully applied it to these exercises. Thank you for your participation!
