### ISSUE TITLE
Samuel Fianyo-Adovor

### ISSUE THREAD

**Issue by Ejw1995** [SERVIR-WA/GALUP#87]
[SAMUEL FIANYO-ADOVOR_EXERCISE 1.pdf](https://github.com/SERVIR-WA/GALUP/files/6765842/SAMUEL.FIANYO-ADOVOR_EXERCISE.1.pdf)
[SAMUEL FIANYO-ADOVOR_EXERCISE 2.pdf](https://github.com/SERVIR-WA/GALUP/files/6765845/SAMUEL.FIANYO-ADOVOR_EXERCISE.2.pdf)
1. Please "drag & drop" exercise 1 pdf file below.

2. Please "drag & drop" exercise 2 pdf file below.

3. Please UPDATE THE TITLE of this "Issue" in the title bar above with your name.

4. If you haven't done so, please go back to Module 1 and make sure to take
   the post-training survey. Participating in surveys is required for receiving
   the "GALUP Certificate" by the University of Florida.

**Comment by JuliePeeling** [comment]
Well done, Samuel. You clearly grasped the material outlined in Module 1 and successfully applied it to these exercises. Thank you for your participation! Please be sure to fill out the post-Module survey before you begin the next Module.
